### ISSUE TITLE
[BUG] 429 Too many requests, yet I can still access (all?) features

### ISSUE THREAD

**Issue by sigaloid** [austinhuang0131/barinsta#1016]
- [X] My app is on the latest version. I understand that any other version is not supported.
- [X] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Shows throttled error at launch yet I can still view chats, posts, etc. Sounds like an issue with a specific URL returning 429, but the rest of them working fine. 
## Steps

1. Open barinsta
2. See throttled error
3. Scroll through chats, etc without issue

## Environment

 - Device: LG G7
 - Android version: 9

## Additional info

Have changed IP about 6 times now, all "throttled". If this is simply an

**Comment by austinhuang0131** [comment]
Activity notifications?

**Comment by sigaloid** [comment]
I can access them, yeah.

I actually was unaware of today's [outage](https://downdetector.com/status/instagram/) so this is probably out of this project's hands, sorry. (excepting possibly the 429 error specifying which endpoint failed? but that's a very rare occurrence). Feel free to close.
