### ISSUE TITLE
Search button in our timeline too

### ISSUE THREAD

**Issue by moshpirit** [austinhuang0131/barinsta#1029]
The timeline is probably where most of the time we are, so it makes sense that something as useful as a searching button is present in this screen.

It's not a big thing but it bothers me a bit going to my profile everytime I want to search anything

**Comment by austinhuang0131** [comment]
there'll eventually be a post button so adding a search is gonna clutter

**Comment by moshpirit** [comment]
How about an option to choose between one or the other? I'm the kind of user that uploads nothing
