### ISSUE TITLE
[FTR] More intuitive way to exit Profile search

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1039]
When you go to the Profile tab, there's the option to also search for other users' profiles. When I do that and open their profile, the only way to return back to my profile (the default Profile tab state) is to press the back button/swipe gesture on my phone.

So I have two suggestions I think would make this more intuitive:
- Add a back button to the most left side next to their account name (this would be shown only when on someone else's profile via search and would take you back to your profile)
- Tapping the Profile tab in the bottom navigation should also take the user back to the default Profile page (my profile) if they are on someone else's profile (currently it does nothing in this case – you stay on their profile)

**Comment by ammargitham** [comment]
If you are using GitHub builds, you can try the latest nightly build and check if this is still applicable.

**Comment by Martin5001** [comment]
> If you are using GitHub builds, you can try the latest nightly build and check if this is still applicable.

I can't seem to find it anywhere. The latest release I see in GitHub releases page is from April. Or where do I get the nightly build?

**Comment by ammargitham** [comment]
> I can't seem to find it anywhere. The latest release I see in GitHub releases page (19.2.1 (62)) is from April. Or where do I get the nightly build?

[Here](https://t.me/BarinstaBuilds) or you can download the artifact zip from [here](https://github.com/austinhuang0131/barinsta/actions/runs/841902260).

**Comment by Martin5001** [comment]
Thanks, I checked the latest build and I think it solves the issue.
