### ISSUE TITLE
[FTR] Don't show "Recommended users" button when not eligible for chaining

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1040]
If I tap this button:
![20210411_163546](https://user-images.githubusercontent.com/35201200/114308743-25f60300-9ae5-11eb-9d28-1235688b67b5.jpg)
I get this, which I assume is not a bug, but Instagram limitation (?):
![Screenshot_20210411-163315_Barinsta](https://user-images.githubusercontent.com/35201200/114308814-605fa000-9ae5-11eb-9bf9-f76a614f04a2.jpg)

So I'd like to suggest this enhancement: Would it be possible to first check if the profile is "eligible for chaining" and show the "Recommended users" button only in that case and hide it otherwise?

**Comment by austinhuang0131** [comment]
I have not seen "not eligible for chaining" before, you probably need to give me the username

**Comment by Martin5001** [comment]
> I have not seen "not eligible for chaining" before, you probably need to give me the username

Well it seems to happen with every profile I follow (both private and public) as well as some I tried randomly searching, including big ones like BBC, National Geographic, NASA etc. So it might be a bug after all.
For more information: I'm using Barinsta version 19.2.0 from F-Droid. My device is Samsung Galaxy J7 (j730f) running Android 9. I'm logged into Barinsta using my Facebook account, not email and password, with 2FA enabled.
