### ISSUE TITLE
[FTR] Don't show Add to favourites for my own profile

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1047]
I think the Add to favourites button should only be visible for other profiles but not my own. This would limit clutter and be more intuitive.

(Because why would I need to add my own profile to favourites, when it's already easily accessible from the Profile navigation tab, which is always visible even if you reorder the navigation in settings.)

**Comment by stamatiap** [comment]
Hi, I could work on this! Can you please assign it to me?
