### ISSUE TITLE
[BUG] "Liked" section text selected when loading

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1048]
If I go to my profile and tap on Likes, the Liked page is loading and the last letter of my user name appears to be selected like when copying text. After the content loads, it appears normal again.

![20210411_211402](https://user-images.githubusercontent.com/35201200/114318049-69636800-9b0b-11eb-8b0f-517e8b505fd3.jpg)

EDIT: The same happens if you tap on the Tagged button and the Tagged section is loading.

I'm using Barinsta 19.2.1 from GitHub running on Samsung Galaxy J7 (j730f) with Android 9

**Comment by ammargitham** [comment]
We just set the subtitle on the actionbar. The actionbar is not a customview created by us. So we don't have control how it behaves.
