### ISSUE TITLE
[FTR] Redundant button in post view

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1054]
If you go to someone's profile, tap on a post to view it, then you can tap on the post again to show/hide the panel with the like button etc. When you are there, this (see screenshot) button does nothing, so it should probably be removed (or placed somewhere it could actually be used).
![20210412_114442](https://user-images.githubusercontent.com/35201200/114375757-4c6b7b00-9b85-11eb-8f72-347c407dc6fc.jpg)

**Comment by austinhuang0131** [comment]
that's the caption button

it should hide on empty captions no??

**Comment by Martin5001** [comment]
> that's the caption button
> 
> it should hide on empty captions no??

Actually now I noticed it was hidden the first time yes, but then it showed again after I tapped the post.
1:
![20210415_170316](https://user-images.githubusercontent.com/35201200/114891863-8b5f3200-9e0c-11eb-8732-f85a535ecc0f.jpg)
2:
![20210415_170305](https://user-images.githubusercontent.com/35201200/114891933-9b771180-9e0c-11eb-89de-61a9670d79ae.jpg)
3:
![20210415_170253](https://user-images.githubusercontent.com/35201200/114891977-a467e300-9e0c-11eb-9df0-9f42d7861e3c.jpg)

**Comment by ammargitham** [comment]
N/A after 2f4eff741e8c7dc9ca4c98dadecd4e8465915e9b
