### ISSUE TITLE
[FTR] Load more posts when using 3 columns layout

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1063]
![20210412_155846](https://user-images.githubusercontent.com/35201200/114406923-36bb7d00-9ba8-11eb-9cb2-bbf99e36c537.jpg)
This is the default state without scrolling to load more – the posts don't take up all available space. If I scroll, more are loaded but then there's still space left at the "end" of the page.

**Comment by austinhuang0131** [comment]
This was done in a certain past version (fetch more pages on first load) but people didn't like it (slow).
