### ISSUE TITLE
[FTR] Video player speed control UI enhancement idea

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1066]
I think it would look great to have this:
![20210412_164835](https://user-images.githubusercontent.com/35201200/114414565-370b4680-9baf-11eb-8cfa-d0edc5378e9d.jpg)
Turn into this:
![20210412_164851](https://user-images.githubusercontent.com/35201200/114414610-42f70880-9baf-11eb-9361-22d3f65f5105.jpg)

**Comment by ammargitham** [comment]
N/A after 2f4eff741e8c7dc9ca4c98dadecd4e8465915e9b
