### ISSUE TITLE
[BUG] Story highlight title doesn't change when going to next highlight

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1075]
If you go to a profile with multiple story highlights – they have different names, for example Me, Friends and Dog. If you tap on Me for example and click through it to the next group (Friends), you'll still see the previous title (Me). If you then go to the next (Dog) you'll still see "Me" in the title. But the title will update correctly if you exit the stories group and open the next by tapping on it directly.

**Comment by tablesturn** [comment]
I can confirm this issue. Fun fact: I encountered the bug in a highlight called "Me", exactly like @Martin5001 
However, it is independent of the highlight name.
