### ISSUE TITLE
[BUG] Deleting downloaded post from notification leaves corrupted file

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1092]
If I download a post and then tap Delete in the notification, it seems the file doesn't get deleted properly. The image is not visible in my file manager, but is still shown as corrupted image in my gallery (I have to delete it from there to get rid of it).

![20210414_174035](https://user-images.githubusercontent.com/35201200/114746741-5c838600-9d50-11eb-80c0-a416b57cf809.jpg)

Barinsta is the only app that causes this issue for me, other apps delete their files just fine. I'm using Samsung gallery app, Barinsta 19.2.1 on Samsung Galaxy J7 running Android 9. If you need any more details, feel free to ask.

**Comment by ammargitham** [comment]
This won't be a problem [once migrated to SAF](https://github.com/austinhuang0131/barinsta/pull/934).

**Comment by Martin5001** [comment]
@austinhuang0131 This issue still occurs on build 65624f0
