### ISSUE TITLE
[FTR] Stories Swipe Link confirmation

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#1101]
if user see stories where have function "Swipe up"
and click "More" App auto open browser
i think the not good idea, because user not see link and this not security

Maybe better show popup window and show link? (if user want go to link he tap on link if not close popup)

**Comment by stamatiap** [comment]
@austinhuang0131 can you please assign this to me? I'm thinking about adding an alert dialog after tapping on "See More" so the user can choose if they want to open the link or not.

**Comment by xbvrhlmb** [comment]
need add translate for other lang
