### ISSUE TITLE
Received shadowban from Instagram

### ISSUE THREAD

**Issue by LifelessMuffin** [austinhuang0131/barinsta#1107]
Hi guys, it's been 3 months since I've started using this amazing app, but in the past weeks Instagram started blocking my account saying I was victim of phishing asking me to reset my password (requested via instagram.com, I double checked the site to be sure before changing it) plus my account is a long time secured by 2fa. I strongly suspect that Barinsta is seen by Instagram as 3rd party and by so they try to block it or something..
It never happened before, just from when I started using this app.

**Comment by austinhuang0131** [comment]
did you approve ("this is me") your Barinsta logins

**Comment by austinhuang0131** [comment]
whatever the case, do the above
