### ISSUE TITLE
[BUG] Selected Time and Date Format does not apply to direct messages

### ISSUE THREAD

**Issue by PLB42** [austinhuang0131/barinsta#1134]
- [X ] My app is on the latest version. I understand that any other version is not supported.
- [X ] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

When an alternative time/date Format is selected, it applies to posts, but not the DM tab.

## Steps

1. Change date format in Settings/Locale/
2. Go To Direct Messages Tab
3. Time/date format used there is still hh:mm and M/d/yy

## Environment

 - Device: OnePlus Nord (AC2003)
 - Android version: 11

![Screenshot_20210420-190041](https://user-images.githubusercontent.com/75607210/115436299-1ecca480-a20b-11eb-9f29-29e2029a4ad4.jpg)
![Screenshot_20210420-190224](https://user-images.githubusercontent.com/75607210/115436305-1ffdd180-a20b-11eb-9244-e5edb552a924.jpg)
![Screenshot_20210420-190234](https://user-images.githubusercontent.com/75607210/115436308-1ffdd180-a20b-11eb-9176-4501027cc2f8.jpg)

**Comment by ammargitham** [comment]
This is kept purposely so that the custom long date formats don't overflow the subtitle.
