### ISSUE TITLE
[FTR] DM – Add margin between chat bubble and bottom controls

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1135]
Just a minor enhancement: It would look better with some space added in between here for visual separation. (This is at the end of the chat page, no further scrolling possible.)
![20210420_204433](https://user-images.githubusercontent.com/35201200/115448209-b802b780-a219-11eb-80b6-9578f5787a11.jpg)

**Comment by xbvrhlmb** [comment]
#969 +
