### ISSUE TITLE
[BUG] DM – reaction menu "plus" button doesn't work

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1137]
If you long press on a message in DMs, this button doesn't work:
![20210420_213502](https://user-images.githubusercontent.com/35201200/115454040-a1ac2a00-a220-11eb-9857-c4c92eb0f4b0.jpg)
(I suppose it's meant to allow you to select a different emoji?)

Barinsta v19.2.1
Android 9
Samsung Galaxy J7

**Comment by ammargitham** [comment]
Yes, I added it, but couldn't finish it due to various reasons.

**Comment by XanXus96** [comment]
@ammargitham if you can share the branch maybe me or someone else would work on it

**Comment by ammargitham** [comment]
@XanXus96 I've already done some work on it. Will be pushed soon. There are lot of other feature requests pending which you can take up.
