### ISSUE TITLE
[BUG] DM reactions are sent but don't show on my side

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1145]
If I send any other emoji than ❤️ from the reactions panel in DM, it is correctly received by the other participant but I don't see anything on my end, it's as if I never sent that reaction.

EDIT: it showed correctly after refreshing, so maybe this was my mistake, sorry. But anyway, it should show the reaction on my side immediately after it's sent without needing refresh because it's confusing if you don't see whether you actually sent that reaction or not.

Barinsta v19.2.1
Android 9
Samsung Galaxy J7

**Comment by ammargitham** [comment]
Was fixed in eed4036ad94ff29636cabd39fc888e8618a60d9c
