### ISSUE TITLE
[FTR] DM visual enhancement – darker colour in dark theme

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1147]
This is really just a minor tweak but I think the chat bubble here would look better with a bit darker colour:
![20210422_124221](https://user-images.githubusercontent.com/35201200/115702099-cb706880-a368-11eb-898f-3392b19eef49.jpg)
For example like this:
![20210422_124248](https://user-images.githubusercontent.com/35201200/115702242-f9ee4380-a368-11eb-8c35-5a35a6540e6b.jpg)
(This specific colour is hex #303030)

**Comment by austinhuang0131** [comment]
Duplicate of #448

**Comment by Martin5001** [comment]
Oh, sorry for the duplicate :) Didn't realize this would be covered by that.
