### ISSUE TITLE
[BUG] Soundcloud song embed in story shows as Spotify's

### ISSUE THREAD

**Issue by yant0** [austinhuang0131/barinsta#1151]
- [ ✓ ] My app is on the latest version. I understand that any other version is not supported.
- [ ✓ ] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Soundcloud song shows Spotify redirect title. when opened it redirected to Soundcloud (app)

## Steps

1. Open app
2. Open story
3. Search a story with a Soundcloud song

## Environment

 - Device: Asus Zenfone Max Pro M1
 - Android version: 9

## Additional info

![Screenshot_20210423-051834](https://user-images.githubusercontent.com/80298071/115792601-c35e0a80-a3f4-11eb-9da6-020580f4e7a4.png)

**Comment by austinhuang0131** [comment]
because i thought spotify is the only supported embed app, so that's why it says spotify

for my own use:

```json
        "story_app_attribution": {
          "app_action_text": "Play on SoundCloud",
          "app_icon_url": "https://scontent-lga3-1.cdninstagram.com/v/t51.12442-15/40047808_234523723873003_1398045721031057695_n.png?_nc_ht=scontent-lga3-1.cdninstagram.com&_nc_ohc=emYrZVrZA-EAX-HFOtQ&edm=ALCvFkgAAAAA&ccb=7-4&oh=6648406b2fd36dcd8499bce05ea9579b&oe=60A8AB54&_nc_sid=643ae9",
          "content_url": "https://soundcloud.app.goo.gl/Nqxvc76j7iaR7fgx9",
          "id": 19507961798,
          "link": "com.soundcloud.android",
          "name": "SoundCloud"
        }
```

**Comment by Martin5001** [comment]
Also note that apparently songs can be uploaded from Shazam too. So this probably needs to be added as well.
