### ISSUE TITLE
[BAN] Error loading profile! Is the user name valid? If so you may be rate limited.

### ISSUE THREAD

**Issue by beng7** [austinhuang0131/barinsta#1153]
## Answer honestly. All boxes must be checked for this report to be considered.

- [x] My app is on the latest version available on GitHub or F-Droid. I understand that any other version is not supported.
- [x] I certify that all actions I have performed on the app constitute human behaviour. I am using the app responsibly and in a way identical to using the official app. Specifically, I did not perform botting or automated key clicks.
- [x] I have considered other possible reasons for my ban, and I cannot find any substantial claim other than the usage of this app.

## Answer honestly. Check accordingly to your situation.

- [ ] I had prior rule violations on Instagram, specifically:
- [ ] I have admitted the use of Barinsta on Instagram.
- [ ] I have admitted the use of Barinsta to a friend who uses Instagram.
- [ ] I have modified the source code of the app that I use, other than what is present in this repo. Specifically:

**Comment by ammargitham** [comment]
IP rate limit is not a ban.

**Comment by beng7** [comment]
Hi
This is the error message that I get lately.
I never had an Instagram account (some of these mandatory questions you ask to report a ban are therefore irrelevant in this case so i suspect this issue will not even be looked at as you expect answers yet it is a genuine issue...); i use barinsta merely to follow accounts I'm interested in / no publication, comments, replies whatsoever so i use barinsta without any login.
I believe the issue is Instagram noticed these barinsta anonymous calls and banned them.
Thanks a lot if you can correct this issue.
Regards

**Comment by beng7** [comment]
@ammargitham 
Thanks, i was not aware of the post.
