### ISSUE TITLE
[BUG] Strange text wrapping in comments view

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1165]
![20210426_163853](https://user-images.githubusercontent.com/35201200/116102133-b79d6d00-a6ae-11eb-8e62-c5069f4fb3eb.jpg)

As you can see on the screenshot the username can fit on the screen and the text is not wrapped at first, but on the next comments it is wrapped and not even to the same length. It should display in full length as on the first comment.

**Comment by ammargitham** [comment]
Fixed with 074ee18c9dbdc97a5a0620ebcbb4b812e7b24a3c
