### ISSUE TITLE
[BUG] Video player progress bar bug

### ISSUE THREAD

**Issue by warren-ru** [austinhuang0131/barinsta#117]
The latest version from F-droid. Previous version had the same bug.
Animation for video loading is active all the way.
![Screenshot_20200904_101137_me austinhuang instagrabber](https://user-images.githubusercontent.com/69246897/92195570-8c53dc80-ee97-11ea-9793-05464f8ab180.jpg)

**Comment by ammargitham** [comment]
This is a known issue. Will be fixed in upcoming update.

**Comment by ammargitham** [comment]
Not relevant since #245
