### ISSUE TITLE
[BUG] Discover tab shows nothing

### ISSUE THREAD

**Issue by bluecheeser** [austinhuang0131/barinsta#1172]
![Screenshot_2021-04-27-16-23-11-911_me.austinhuang.instagrabber.jpg](https://user-images.githubusercontent.com/81776134/116230101-dfef9f00-a774-11eb-935b-6a757f2023d5.jpg)

**Comment by austinhuang0131** [comment]
I can't reproduce it.

It's probably upstream (on Instagram's side) so I can't do anything about it either.
