### ISSUE TITLE
Question/request: Do Crowdin changes (not new) also get automatically commited?

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1179]
I'm not sure, but it seems that when there is already a translation on Crowdin, and a corrected/changed translation is submitted, it doesn't make it to the auto commits.

Crowdin prioritizes newer translations if there's none approved by a proofreader. (We currently don't have a proofreader for Czech.) So those changes should probably be reflected in the commits too?

If so, please could you make sure to include these changes? (I made some corrections for Czech translation – there were some mistakes and inconsistencies – but I don't see them in the commits.) Thank you

PS: Didn't know whether to put it there or the discussion tab, but since this is basically like a pull request, just I don't have the actual files to commit, so I'm writing it here.

**Comment by austinhuang0131** [comment]
> I'm not sure, but it seems that when there is already a translation on Crowdin, and a corrected/changed translation is submitted, it doesn't make it to the auto commits.

Crowdin checks for all files every 30 minutes and will commit all the changes. It's not instant.

> Crowdin prioritizes newer translations if there's none approved by a proofreader. (We currently don't have a proofreader for Czech.) So those changes should probably be reflected in the commits too?

Your edits should be present in #1045 so please check as needed.

**Comment by Martin5001** [comment]
Oh, I see, I somehow missed that. Thank you.
