### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by uluchann** [austinhuang0131/barinsta#1191]
after the second to the latest update; Barinsta fails to connect to the Instagram (after the latest update not working either, I finally made the time to open an issue. sorry for that). 

In the main screen it says; "You can login via More>>Account..." and when I go tap on the "Add account", it just displays the Instagram logo in the middle. "refresh" button only makes the logo refresh. "get cookies" button gives the info box saying "Error loading cookies". I am adding the screenshot.

![barinsta](https://user-images.githubusercontent.com/60944279/116717310-6e685880-a9e1-11eb-8c20-104ce057b563.jpg)

Barinsta version: 19.2.1-fdroid(62)
Android: 7.0 with Kernel of: 3.10.84

Thanks in advance. Happy to include any other information needed.

**Comment by austinhuang0131** [comment]
Please check your device's WebView installation, and update if necessary. The official Android System WebView is recommended.

**Comment by uluchann** [comment]
Thank you very much Austin! I am sorry to bother with something as simple as this. Updating WebView worked a charm.

Cheers and best in life!
