### ISSUE TITLE
[BUG] Low resolution videos

### ISSUE THREAD

**Issue by Mat6845** [austinhuang0131/barinsta#1196]
## What's happening?

Videos in Feed and Story are downloaded in low resolution since version 19.1.0 "Beaver Tail" (from Github)

I tested the last release available on F-droid, version 19.2.1, the same happened.

## Environment

 - OEM: Samsung
 - Android version: 10

**Comment by austinhuang0131** [comment]
okay, screw this, i'm just gonna say all your phones are 3000x3000

**Comment by Mat6845** [comment]
Sorry, my phone is 720x1562

**Comment by Mat6845** [comment]
> okay, screw this, i'm just gonna say all your phones are 3000x3000

Sorry, my phone is 720x1562

**Comment by austinhuang0131** [comment]
your own phone size doesn't matter, we basically tell instagram that you're using another phone
