### ISSUE TITLE
Anonymous ratelimit question

### ISSUE THREAD

**Issue by acimanx** [austinhuang0131/barinsta#1203]
## Answer honestly. All boxes must be checked for this report to be considered.

- [X] My app is on the latest version available on GitHub or F-Droid. I understand that any other version is not supported.
- [X] I certify that all actions I have performed on the app constitute human behaviour. I am using the app responsibly and in a way identical to using the official app. Specifically, I did not perform botting or automated key clicks.
- [X] I have considered other possible reasons for my ban, and I cannot find any substantial claim other than the usage of this app.

## Answer honestly. Check accordingly to your situation.

- [ ] I had prior rule violations on Instagram, specifically:
- [ ] I have admitted the use of Barinsta on Instagram.
- [ ] I have admitted the use of Barinsta to a friend who uses Instagram.
- [ ] I have modified the source code of the app that I use, other than what is present in this repo. Specifically:

## Provide your communication with Instagram, without private information of you.

I'm not sure if it's a bug or ban by Instagram. I receiving message in barinsta: 
"Your IP has been rate limited by Instagram..."
I see this message already for a several weeks. Before I didn't actively used barinsta, just used a search a couple of times and visited 2-3 profiles.

**Comment by austinhuang0131** [comment]
Nope, that's a ratelimit, not a ban.

https://redd.it/msxlko
