### ISSUE TITLE
[BUG] Special character/emoji gets included in hashtag link

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1204]
(This bug may be upstream in the library you're using, but I'll report it anyway in case you still can do something about it.)

This hashtag ♡#MK♡ in someone's bio got converted into a link including the heart symbol after the hashtag. Thus the link became invalid and throws an error. (I tried with stock Instagram and it works fine there.)

Maybe you could add a filter excluding any special characters leaving only standard letters and numbers?

**Comment by Martin5001** [comment]
@austinhuang0131 I see now that you made some changes it correctly doesn't include the first heart symbol but it (still/now – maybe it wasn't there before, I don't remember) includes the one at the end of the hashtag. (Barinsta 19.2.2)

**Comment by Martin5001** [comment]
(Sorry for the deleted mention comment. I thought this was fixed and basically reported it again thinking it was a different issue. But it's still not fixed in 19.2.2, right?)

**Comment by austinhuang0131** [comment]
@ammargitham merge the pr
