### ISSUE TITLE
[FTR] UX enhancement – Open profile from story vs from post inconsistency

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1215]
When you're going through posts, you can view author's profile by simply tapping on their name above the post. But when you're viewing a story, it's different – the user name is shown there too, but doesn't have any function. Instead to open the profile you have to use the three dots menu in the top right corner.

I got used to it but at first it was confusing – I was just expecting it to behave the same as in post view, but it didn't. So I think this should be made consistent – tap on the user name instead of the three dots menu to open the profile.

**Comment by austinhuang0131** [comment]
ActionBar limitation
