### ISSUE TITLE
[BUG] Time goes over last emoji

### ISSUE THREAD

**Issue by victorbnl** [austinhuang0131/barinsta#1222]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Sometimes the time goes over the last emoji of the message. I don't if this is related to the fact it is an emoji and not normal text but I guess yes as it seems to work normally with other text

![Screenshot_20210508-144232_Barinsta](https://user-images.githubusercontent.com/39555268/117539696-139bb600-b00c-11eb-8287-72cce5f42724.png)

## Steps

1. Send a message of about two lines with an emoji at the end (for example `So here you can see the timestamp overlaps lol 😂` works on my phone)
2. 

## Environment

 - Device: Xiaomi Mi A2 Lite (daisy)
 - Android version: 10 (custom ROM)

**Comment by ammargitham** [comment]
@victorbnl I've added a change which may resolve this issue. If you use our nightly builds, you can check it tomorrow when it builds.

**Comment by victorbnl** [comment]
Ok I'll test 👍

**Comment by victorbnl** [comment]
It works!
