### ISSUE TITLE
[FTR] reels support in future please

### ISSUE THREAD

**Issue by ansarimohammed422** [austinhuang0131/barinsta#1241]
**Describe the solution you'd like**
Can you add support for reels

**Comment by austinhuang0131** [comment]
Reels are posts so they're visible in the post feed.

We will not add a dedicated Reels tab.

**Comment by hkhkhk009** [comment]
Not all reels are visible on post tab on instagram itself. So, it should be fixed by either merging reels and posts tab, or making separate tab for it. It should be repoened.

**Comment by austinhuang0131** [comment]
example for this claim?

**Comment by hkhkhk009** [comment]
Example: https://www.instagram.com/reel/COc0QhdD_u6/
This reel is not visible on this profile: https://www.instagram.com/niveditalakraa/

**Comment by austinhuang0131** [comment]
i guess they changed it

**Comment by ansarimohammed422** [comment]
So can you please add support for reels @hkhkhk009 thanks for supporting this issue

**Comment by austinhuang0131** [comment]
It does seem that users are allowed to hide reels from profile page which is a problem

**Comment by austinhuang0131** [comment]
superseded by #1600
