### ISSUE TITLE
[BUG] Discover tab categories invisible

### ISSUE THREAD

**Issue by ruzko** [austinhuang0131/barinsta#1244]
- [ √] My app is on the latest version. I understand that any other version is not supported.
- [ √] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Discover categories are invisible, and can't be picked. The invisible posts/categories above the text "for deg" can still be picked.

![Screenshot_20210513-105932](https://user-images.githubusercontent.com/75946143/118106154-97bfb600-b3dd-11eb-90ab-7c5b2d23c01b.png)

The posts reached by tapping above "for deg", are visible and can be picked.
![Screenshot_20210513-111247](https://user-images.githubusercontent.com/75946143/118106392-d8b7ca80-b3dd-11eb-8bf6-61f05fc64056.png)

## Steps

1. Click on discover button on bottom app menu
2. Experience bug.

## Environment

 - Device: Motorola moto g⁸ plus (XT2019-1)
 - Android version: 10

## Additional info

Running unlocked bootloader

**Comment by austinhuang0131** [comment]
It's suspected to be a regional issue so that depends entirely on the upstream (Instagram)
