### ISSUE TITLE
[LOCK] account locked, but not banned

### ISSUE THREAD

**Issue by benwaffle** [austinhuang0131/barinsta#1249]
I know a lock is not a ban, but not sure if its expected so I'm reporting it.

## Answer honestly. All boxes must be checked for this report to be considered.

- [x] My app is on the latest version available on GitHub or F-Droid (19.2.1-fdroid). I understand that any other version is not supported.
- [x] I certify that all actions I have performed on the app constitute human behaviour. I am using the app responsibly and in a way identical to using the official app. Specifically, I did not perform botting or automated key clicks.
- [x] I have considered other possible reasons for my ban, and I cannot find any substantial claim other than the usage of this app.

## Answer honestly. Check accordingly to your situation.

- [ ] I had prior rule violations on Instagram, specifically:
- [ ] I have admitted the use of Barinsta on Instagram.
- [ ] I have admitted the use of Barinsta to a friend who uses Instagram.
- [ ] I have modified the source code of the app that I use, other than what is present in this repo. Specifically:

## Describe your case, including your usage pattern, but without private information.
Just looking at everything like normal, as well as comparing following/follower counts

## Provide your communication with Instagram, without private information of you.
I was able to put in a 6 digit code that was texted to me and change my password to get back in.

**Comment by austinhuang0131** [comment]
not a ban

try not to compare following/follower counts too often
