### ISSUE TITLE
[BUG] Emoji button no longer working after #1181 fix

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1252]
In the latest nightly build, you fixed the issue with emoji keyboard (#1181) but the emoji button stopped working since.

Android 9
Samsung Galaxy J7

**Comment by ammargitham** [comment]
What do you mean by stopped working? Can you provide steps to reproduce?

**Comment by Martin5001** [comment]
So I was going to provide the steps and was going through it again, and it now works after restart. Sorry, don't know what happened, but it's fine now.
