### ISSUE TITLE
[FTR] Exclude my own profile from mention links

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1253]
If someone mentions me in a comment, the link to my profile is clickable like any other. But that is unnecessary (why would I go to my own profile) and also if the comment is one line or just the tag, it can make it harder to reply to/like that comment, because I can tap the link accidentally. So it would be better if my own profile link was never clickable.

**Comment by ammargitham** [comment]
The mention parsing logic does not have the context of the text message. So excluding self profile from being linked is not possible. However the reply-to and reactions not working if its just a link is a bug.

**Comment by ammargitham** [comment]
I checked and found no issues with long click and reply if the message is just a mention.

**Comment by Martin5001** [comment]
I'm not sure if I remember correctly, I think it was changed, so now there's really no issue, right

**Comment by austinhuang0131** [comment]
previously you could click outside the text (but still within the comment item) to reply but this is no longer applicable due to changes
