### ISSUE TITLE
[FTR] Focus search input after tapping Search icon

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1261]
In the nightly build, if I tap the search icon I then have to tap into the input to focus it and show keyboard. I think it should get focus automatically so I can start typing right away.

**Comment by Martin5001** [comment]
@austinhuang0131 Since this is now closed, is it supposed to be in the current nightly build 7ca0d51 already? Because I currently don't see a change. Just to let you know in case.

**Comment by austinhuang0131** [comment]
This is on release, but you must enable it in settings

**Comment by Martin5001** [comment]
Ah, thanks
