### ISSUE TITLE
[BUG] Search keeps previous search query after going back from post

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1262]
In the latest nightly build, when you search and then go to the result and then come back to search, the previous search is still in the input and the results are still shown. You can also see this when switching between search category tabs. Type some text, then switch to different category, then go back to the previous tab, then delete the text and go to the other tab. You'll see the previous results stay there for a moment before being reloaded (in this case to a blank page, since you deleted the text from the search bar).

**Comment by austinhuang0131** [comment]
i fail to see how this is a bug

**Comment by Martin5001** [comment]
> i fail to see how this is a bug

Well, maybe it's not, don't know, but I mean that if you have performed the search and you then want to do another, you probably don't want to need to delete the previously entered text first. You want to do a new search – empty search box, ready for you to type.

**Comment by ammargitham** [comment]
This is normal UX of a search component throughout the web. Navigating from a search result list to a result and navigating back should take you back to the prev screen with the prev results.
