### ISSUE TITLE
[BUG] Refreshing "Suggested users" causes the app to crash

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1268]
If you go to this screen:
![20210516_104538](https://user-images.githubusercontent.com/35201200/118391311-f0888c00-b633-11eb-9aa6-7dc1c9c48ca0.jpg)
![Screenshot_20210516-104411_Barinsta](https://user-images.githubusercontent.com/35201200/118391313-f4b4a980-b633-11eb-8fea-7efea49f9846.jpg)
and pull down to refresh, the app crashes.
Android 9, Samsung Galaxy J7

**Comment by austinhuang0131** [comment]
cannot reproduce

**Comment by Martin5001** [comment]
> cannot reproduce and also need crash dump

That's the "logcat", right? I can give you that in a few days when I get to my computer.

**Comment by austinhuang0131** [comment]
I mean did you have Sentry on? If so give me an approximate timestamp on when it happened

Otherwise, yeah, logcat should show the crash dump as well

**Comment by Martin5001** [comment]
Ok, I have Sentry and I now reproduced the bug at 21:26. Feel free to ask if you need anything else.

**Comment by austinhuang0131** [comment]
I didn't get anything on Sentry (note that most adblock host files have Sentry fully blocked), might as well dig the logcat

**Comment by Martin5001** [comment]
Oh, I haven't thought of that, I actually do have an adb locker. So now you should get something at 21:40. (Or I'll just try the logcat maybe tomorrow.)

**Comment by austinhuang0131** [comment]
I still don't have it...

Try the logcat if you can, sorry for inconvenience.

**Comment by Martin5001** [comment]
[logcat.txt](https://github.com/austinhuang0131/barinsta/files/6506415/logcat.txt)
I reproduced the crash around 8:46 three times (the last would be close to 8:47), hope it helps.

**Comment by austinhuang0131** [comment]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at awais.instagrabber.adapters.NotificationsAdapter$1.areItemsTheSame(NotificationsAdapter.java:2)
       at androidx.recyclerview.widget.AsyncListDiffer$1$1.areItemsTheSame(AsyncListDiffer.java:5)
       at androidx.recyclerview.widget.DiffUtil.calculateDiff(DiffUtil.java:26)
       at androidx.recyclerview.widget.AsyncListDiffer$1.run(AsyncListDiffer.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by Martin5001** [comment]
@austinhuang0131 It was working but in current build it crashes again when I open it (immediately, without the refresh even) so probably should be reopened. Will get crash log tomorrow. (Posting now in case you already knew the cause without it.)

**Comment by Martin5001** [comment]
In the latest build, it works again
