### ISSUE TITLE
The problem with no explore topics

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/barinsta#1271]
Since this issue seems to occur on a per-account or per-region (by IP) basis, and neither maintainer has this issue, anyone affected can try to debug this issue for us...

1. We'll assume you're using a Chromium-based browser on a computer. Firefox probably has a similar procedure.
2. Log into Instagram on browser, if you haven't done it yet. Stay on Instagram (any page under `www.instagram.com` should work).
3. Open the Developer Panel. You can right click anywhere, then "Inspect". Or click the 3 dots, then "More tools", then "Developer Tools".
4. Follow [this article](https://developer.chrome.com/docs/devtools/device-mode/override-user-agent/). For the last step, select "Custom", then put `Instagram 169.3.0.30.135 Android (27/8.1.0; 320dpi; 720x1362; motorola; motorola one; deen_sprout; qcom; pt_BR; 264009054)` (This was the string used for InstaGrabber).
5. Go to console, paste the following script, then hit <kbd>Enter</kbd>.

```js
fetch("https://i.instagram.com/api/v1/discover/topical_explore/", {
  "method": "GET",
  "credentials": "include"
})
.then(response => response.json())
.then((response) => {
  console.log(JSON.stringify(response));
});
```

6. A while later you'll see a big blob of text (not error). Hit "copy" and send it here or to [my Telegram](https://t.me/austinhuang).

Note: You should only do this if you're affected. The script basically returns a list of topics and should not identify a person directly (but may indirectly indicate your interests).

**Comment by austinhuang0131** [comment]
Okay, those affected only have this 1 object for the `clusters` array:

```json
{
      "id": "explore_all:0",
      "title": "For You",
      "context": "",
      "description": "",
      "labels": [],
      "type": "explore_all",
      "name": "For You",
      "can_mute": false,
      "is_muted": false,
      "debug_info": ""
}
```

For comparison, this is what Barinsta expects, whereas `cover_media` is a `Media` object:

```json
{
      "id": "explore_all:0",
      "title": "For You",
      "context": "",
      "description": "",
      "labels": [],
      "type": "explore_all",
      "name": "For You",
      "can_mute": false,
      "is_muted": false,
      "debug_info": "",
      "cover_media": {...},
      "ranked_position": 0
}
```

A mitigation would be to use the first post in the subsequent `items` array as cover, even though it might (and often) not be representative of what users get when they enter the topic

**Comment by Martin5001** [comment]
I think the cover image is often not representative anyway (even when it worked), so maybe using a hand-picked image from unsplash.com or just an icon instead would be better?
