### ISSUE TITLE
[BUG] Dates shown wrong

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1281]
In the GitHub build no. 54 the dates in stories are clearly wrong:

![20210519_211206](https://user-images.githubusercontent.com/35201200/118870723-2903c080-b8e7-11eb-8b90-3badf35d64ec.jpg)
(I guess this is supposed to be 19. 5. 2021)

![20210519_211145](https://user-images.githubusercontent.com/35201200/118870815-3b7dfa00-b8e7-11eb-8b78-df06229fb332.jpg)

Android 9, Samsung Galaxy J7

**Comment by austinhuang0131** [comment]
Need a screenshot of date settings

**Comment by Martin5001** [comment]
Here you go:
![Screenshot_20210520-075319_Barinsta](https://user-images.githubusercontent.com/35201200/118926464-a871ae00-b940-11eb-99b5-12a462ef0272.jpg)
![20210520_075351](https://user-images.githubusercontent.com/35201200/118926478-ac9dcb80-b940-11eb-9d73-d4fd75bc550e.jpg)

**Comment by austinhuang0131** [comment]
"mm" is minutes, "MM" is month. Click the (i) button for more info.

**Comment by Martin5001** [comment]
Oh, what a stupid mistake 😂 sorry
