### ISSUE TITLE
[BAN] Logged out and forced password change due to "suspicious activity"

### ISSUE THREAD

**Issue by Tech-Geek97** [austinhuang0131/barinsta#1288]
## Answer honestly. All boxes must be checked for this report to be considered.

- [X] My app is on the latest version available on GitHub or F-Droid. I understand that any other version is not supported.
- [X] I certify that all actions I have performed on the app constitute human behaviour. I am using the app responsibly and in a way identical to using the official app. Specifically, I did not perform botting or automated key clicks.
- [X] I have considered other possible reasons for my ban, and I cannot find any substantial claim other than the usage of this app.

## Answer honestly. Check accordingly to your situation.

- [ ] I had prior rule violations on Instagram, specifically:
- [ ] I have admitted the use of Barinsta on Instagram.
- [X] I have admitted the use of Barinsta to a friend who uses Instagram.: only my roommate in a face to face discussion.
- [ ] I have modified the source code of the app that I use, other than what is present in this repo. Specifically:

## Describe your case, including your usage pattern, but without private information.
Browsed Instagram feed similar to usage in the native app.
## Provide your communication with Instagram, without private information of you.
No email or similar, only error message while logging in asking for email 2FA and a password change.

**Comment by austinhuang0131** [comment]
not a ban

please remember to confirm every login from another client
