### ISSUE TITLE
[BUG] Caption text covers post

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1292]
I encountered this issue when tapped to show post:
![Screenshot_20210521-202616_Barinsta](https://user-images.githubusercontent.com/35201200/119182521-4cf40d00-ba73-11eb-9625-f2f368554ab7.jpg)
It seems it happens only with long caption texts.
EDIT: one more detail – a way to temporarily fix this is to tap somewhere on the post not covered by the text, this will last until you open the post again

Barinsta e726ba3
Android 9
Samsung Galaxy J7

**Comment by austinhuang0131** [comment]
cannot reproduce (same post)

**Comment by Martin5001** [comment]
Can I help somehow?

**Comment by xbvrhlmb** [comment]
i have this too, maybe if low display size?
![image](https://user-images.githubusercontent.com/43858033/119222895-3c897400-baff-11eb-9412-b3f1c02f8836.png)

**Comment by Martin5001** [comment]
> maybe if low display size?

I have 5.5"

**Comment by xbvrhlmb** [comment]
i have 5.5 too 720x1280 300dpi

**Comment by ammargitham** [comment]
If any of you guys use nightly builds, check this issue in the next nightly and report back

**Comment by Martin5001** [comment]
Will do

**Comment by Martin5001** [comment]
Can confirm this was fixed in the latest nightly build
