### ISSUE TITLE
[BUG] Feed Icon

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#1298]
if open post we see new icon
but if open feed we can see old big icon 
the bug or features ? :)

**Comment by austinhuang0131** [comment]
I don't understand?

**Comment by xbvrhlmb** [comment]
![barinsta](https://user-images.githubusercontent.com/43858033/119228883-d52eec80-bb1d-11eb-9432-a5e2837843b1.png)

Icon in feed gery and big
icon if open post little and colored theme

**Comment by austinhuang0131** [comment]
superseded by #1376
