### ISSUE TITLE
[BUG] CPU load if load user profile

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#1299]
I may be wrong, but when installing the latest version, I noticed a stronger load when opening the profile of people. In the old version, everything was loaded more smoothly and quickly now the load is 100% cpu.
Maybe there is an error somewhere?

only if load profile (more images) other all work fine.

i think the problem because use more RAM to open feed image profile

**Comment by austinhuang0131** [comment]
stale
