### ISSUE TITLE
[TASK] Migrate Date to LocalDate

### ISSUE THREAD

**Issue by ammargitham** [austinhuang0131/barinsta#1309]
LocalDate/LocalDateTime is more feature rich than Date. So it will be overall better to migrate.

**Comment by austinhuang0131** [comment]
Don't see `TextUtils.getRelativeDateTimeString` replaceable. Otherwise it's done.

**Comment by ammargitham** [comment]
We can calculate diff using [Duration](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#between-java.time.temporal.Temporal-java.time.temporal.Temporal-) class.
