### ISSUE TITLE
[BUG] Feed stopped working

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1326]
I think I am not ratelimited (ig website works and other parts of Barinsta too) but the Feed won't load no matter how long I wait. Build 7e00dcc on Android 9 Samsung Galaxy J7 – it worked fine with previous version

**Comment by ammargitham** [comment]
Probably fixed with ce31554687b37aeca7a2a796187633b372455c59

**Comment by austinhuang0131** [comment]
requesting feedback

**Comment by Martin5001** [comment]
Yes, it's fixed. Thanks
