### ISSUE TITLE
[BUG] Videos get stuck

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1332]
Sometimes when I play a video, it gets stuck after a while even though my wi-fi connection is stable. It also doesn't show any loading. It l seems as if the video ended, but it still has more than a half left on the seekbar. This happened a couple of times but doesn't happen consistently. Will try to get more info if needed.

Barinsta nightly on Samsung Galaxy J7 with Android 9

**Comment by austinhuang0131** [comment]
#1418?

**Comment by Martin5001** [comment]
> #1418?

Possibly, I didn't notice it had anything to do with sound but I'll try to focus on that if it happens again.
