### ISSUE TITLE
[BUG] some white text in white theme should be black, and viceversa

### ISSUE THREAD

**Issue by Megver83** [austinhuang0131/barinsta#1338]
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

### White which should be black:
1. Start recording a voice message or open the GIFs search engine in DMs
2. In both cases (the introduced words in GIFs search and voice record timer/"Slide to cancel" phrase) the text is white in the white theme, which is eye-stressful

### Black which should be white or light:
1. In any profile, open the profile photo
2. You'll see that the download button is black with dark text, making it very difficult to read

#### Also
1. Look for a post sent into your DM inbox
2. The account's poster username text is in black, with dark background, unlike short description which is white

## Additional info

<img src="https://user-images.githubusercontent.com/22277674/119686016-4ae7d080-be1c-11eb-8450-2b11427bf8f9.jpg" width="300" /> <img src="https://user-images.githubusercontent.com/22277674/119686239-84204080-be1c-11eb-951c-c7641f60d99d.jpg" width="300" />

**Comment by Megver83** [comment]
@austinhuang0131 I think we should re-open this issue or finish polishing these two details:

1. The trash icon when discarding a voice message
2. The number 5 and 15 inside the circled arrows in videos

<img src="https://user-images.githubusercontent.com/22277674/124068693-59279e80-da11-11eb-9a07-104aae65c6e0.jpg" width="300">

**Comment by austinhuang0131** [comment]
First one is fixed. Second one seems to be an issue with ExoPlayer.
