### ISSUE TITLE
[BUG] story responses don't have read ticks

### ISSUE THREAD

**Issue by Megver83** [austinhuang0131/barinsta#1339]
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Steps

1. Answer a story
2. Got to the DM chat
3. There are no ticks, unlike common messages, so there's no way to know if the other person read your answer

**Comment by xbvrhlmb** [comment]
+ this is not enough
