### ISSUE TITLE
[FTR] Don't store voice messages in internal storage

### ISSUE THREAD

**Issue by Megver83** [austinhuang0131/barinsta#1341]
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

I know this is not strictly a bug, but it's an issue. Recorded voice messages are stored but not removed in the phone's storage. These are useless once sent, would be good if Barinsta automatically removed these files when the message is sent.

**Comment by austinhuang0131** [comment]
The recordings are used to display the sent message locally before refresh. Obviously real-time refresh is ideal (#119) but they aren't gonna be there for _a long while_.

Also I'm sure there'll be people who say they want to keep the recordings and whatnot
