### ISSUE TITLE
[FTR] Register scrolling on bio text

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1343]
If someone has long bio text, it can prevent you from easily scrolling down the page, because the bio text area doesn't register scrolling (only touch to open the context menu with Copy and Translate options). This means you have to find a spot outside the bio text area if you want to scroll. Bio text should not prevent scrolling.

**Comment by xbvrhlmb** [comment]
yea and if user have link in bio you miss swipe to this link

**Comment by austinhuang0131** [comment]
implemented, presumably by https://github.com/austinhuang0131/barinsta/commit/efd3f8cff0f24dd3c05197b30733f9870b03ccd9
