### ISSUE TITLE
[BUG] message date missing at the beginning of a chat

### ISSUE THREAD

**Issue by Megver83** [austinhuang0131/barinsta#1344]
**Is your feature request related to a problem? Please describe.**
Whenever I start a conversation, I cannot see the first message's date until the screen if fulfilled.

**Describe the solution you'd like**
Always show dates, no matter if the screen if filled with messages or not

**Additional context**
This is the problem I refer to:

<img src="https://user-images.githubusercontent.com/22277674/119849742-43d7c580-bee3-11eb-943a-a5d6dd71065b.jpg" width="200" />

The date is shown since the second message only

**Comment by austinhuang0131** [comment]
not reproducible

**Comment by austinhuang0131** [comment]
stale
