### ISSUE TITLE
[FTR] Save Position on Favorites tab

### ISSUE THREAD

**Issue by FOSS-Love** [austinhuang0131/barinsta#1359]
I use barinsta without account, i keep up with accounts by visiting one after the other from my fav tab.

Whenever i visit a profile from fav tab and returns back to fav tab to visit another profile, the fav tab gets refreshed and i have to scroll down to find the account.

It would be great if my favorites page remembers the position.

I don't know the technical possibility of this feature but incase possible it would be great to have.

**Comment by Vonter** [comment]
I would also like to see this feature. I've tried adding it in #1374.
