### ISSUE TITLE
[FTR] Universally Change Profile Picture Size

### ISSUE THREAD

**Issue by yant0** [austinhuang0131/barinsta#1377]
set my profile picture size to small, when i click on post its large.
![Screenshot_20210602-133512](https://user-images.githubusercontent.com/80298071/120435064-f1d0ed00-c385-11eb-861f-c0e873d36156.png)
![Screenshot_20210602-133519](https://user-images.githubusercontent.com/80298071/120435094-fd241880-c385-11eb-8a0f-5ee4ccf552b0.png)

additionally, add option to disable username in posts

**Comment by austinhuang0131** [comment]
Profile picture sizes only apply to layouts, not the post viewer. That's intended.

Because of the username and the full name, the profile picture size _should_ be that big, so it would make little sense to change it without changing the font size, which (in my opinion) is incredibly niche.
