### ISSUE TITLE
[FTR] Changes in animations

### ISSUE THREAD

**Issue by SD61** [austinhuang0131/barinsta#1382]
[FTR] after the last update, the animation became too smooth. before the animation was invisible and it was good. 

- the hard way to add a regulator.
- simple way add disable checkbox
- maybe speed up by 100 milliseconds will be enough

**Comment by Martin5001** [comment]
I got used to it now, but I agree the animations also felt too long to me. And the animation at the top right corner area (search and other icons) is a bit longer than the one for the title on the right. I think they should run simultaneously.

**Comment by Martin5001** [comment]
Especially the Layout settings popup opening and closing animations feel slow.

**Comment by ammargitham** [comment]
Screen transition disable setting has been added in #1542.

As for the layout preferences dialog, I will make it that animation similar to normal dialogs.

**Comment by ammargitham** [comment]
Custom animation for Layout preferences dialog has been removed in e3bf083b52bcc05b3120f25820ad78e4d7eb9afa.
