### ISSUE TITLE
[BUG] Post Translate

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#1383]
easy fix "Post" not translate in other languages
in Feed,DM and other.

![1](https://user-images.githubusercontent.com/43858033/120529371-1ad49a80-c3e5-11eb-842a-656f11bf6cc1.png)

**Comment by Martin5001** [comment]
And I think I saw Followers or Following untranslated too (but not in the profile, but as a heading similar to this one).
