### ISSUE TITLE
[BUG] Buggy Favourite list behaviour (if set as a home tab)

### ISSUE THREAD

**Issue by gvdvg** [austinhuang0131/barinsta#1384]
- [ ] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [ ] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

I accidentally unfav'ed then quickly re-fav'ed an existing fav account which then moved it to the end of the fav list. Upon restart, the account was not on the list and only appeared on the list once I tried to fav another new account.
So now, if I want to fav a new account 'A', I have to fav accounts 'A' AND 'B'. To then fav account 'B', I have to fav account 'C' and so on. 
I hope this makes sense and is replicable.

 - Version: 19.2.2-fdroid(63)
 - Android version: 11 (One UI 3.1)

**Comment by austinhuang0131** [comment]
does not seem to be replicable on latest master

**Comment by gvdvg** [comment]
ok, I was thinking a possible source of corruption was that I saved a backup of my settings (incl. favs) from the previous version and restored them into the latest version, maybe something went wrong there, idk
thanks

**Comment by RickyM7** [comment]
Same here! The last favorite is not visible in the favorites tab, but actually the favorite is there yet and you can see it in the search area.

- Device: Redmi Note 4 (MIUI 11 - Android 7.0) 
- App version: v19.2.2-fdroid

**Comment by austinhuang0131** [comment]
Oh, yeah it seems to hide the last one behind the menu bar.
