### ISSUE TITLE
[BUG] Crashes when rotating

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1392]
1. Turn the phone to landscape
2. Tap on post to view it in full screen (comments and title hidden, only the image is visible)
3. Rotate the phone back to portrait
See the app crash

Android 9
Samsung Galaxy J7

**Comment by ammargitham** [comment]
Can't reproduce in latest builds. Guess it was resolved. Can you confirm?

**Comment by Martin5001** [comment]
Yes it's fixed now

**Comment by austinhuang0131** [comment]
Duplicate of #1457
