### ISSUE TITLE
[BUG] Caption Inside Video

### ISSUE THREAD

**Issue by yant0** [austinhuang0131/barinsta#1394]
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

![Screenshot_20210605-072135](https://user-images.githubusercontent.com/80298071/120874117-4d57d200-c562-11eb-8826-7d4dfcf8e82c.png)

## Steps

1. Open app
2. Look videos
3. Catch bug occur

## Environment

 - Device: asus zenfone max pro m1
 - Android version: 9 stock

**Comment by austinhuang0131** [comment]
Duplicate of #1292
