### ISSUE TITLE
[FTR] tag or mark new users followed / following since instagram removed chronological order followed/following list

### ISSUE THREAD

**Issue by DealsBeam** [austinhuang0131/barinsta#1398]
Since Instagram removed chronological order listing for new followers / followed for both app and now browser, many users are looking for a solution (ie. https://old.reddit.com/r/Instagram/comments/nsbqel/order_of_the_followersfollowing_list/ & https://old.reddit.com/r/Instagram/comments/nsfpyg/you_used_to_be_able_to_see_someones_followers_and/)

So I'm suggesting a feature that allows you to tag or mark users already followed / following so when new users are follow / are followed, you can see them untagged/unmarked, letting users know that this user is a new follower, etc.

**Comment by austinhuang0131** [comment]
Duplicate of #244
