### ISSUE TITLE
Banned account

### ISSUE THREAD

**Issue by 0nse** [austinhuang0131/barinsta#140]
I followed the README that told me I have to report if I get banned using this app. After a few weeks using it exclusively, it has happened. Thus, I now report it and am open for questions.

**Comment by austinhuang0131** [comment]
you have to use the "BAN REPORT" template

```
<!-- Write "x" in the brackets to check -->

## Answer honestly. All boxes must be checked for this report to be considered.

- [ ] My app is on the latest version. I understand that any other version is not supported.
- [ ] I certify that all actions I have performed on the app constitute human behaviour. I am using InstaGrabber responsibly and in a way identical to using the official app. Specifically, I did not perform botting or automated key clicks.
- [ ] I have considered other possible reasons for my ban, and I cannot find any substantial claim other than the usage of InstaGrabber.

## Answer honestly. Check accordingly to your situation.

- [ ] I had prior rule violations on Instagram, specifically:
- [ ] I have admitted the use of InstaGrabber on Instagram.
- [ ] I have admitted the use of InstaGrabber to a friend who uses Instagram.
- [ ] I have modified the source code of the app that I use, other than what is present in this repo. Specifically:

## Describe your case, including your usage pattern, but without private information.

## Provide your communication with Instagram, without private information of you.
```

**Comment by 0nse** [comment]
I'm sorry, I just clicked the link and there was no template to begin with. Thanks for replying.

- [x] My app is on the latest version (GitHub or F-Droid). _At the time the account was banned, 18.2 (F-Droid) was the most recent and I had that installed._ 
- [x] I certify that all actions I have performed on the app constitute human behaviour. I am using InstaGrabber responsibly and in a way identical to using the official app. Specifically, I did not perform botting or automated key clicks: _I don't post content but follow people. However, when my account was initially blocked, I verified it via a shared SMS setvide. It was then banned afterwards._ 
- [x] I have considered other possible reasons for my ban, and I cannot find any substantial claim other than the usage of InstaGrabber: _See above, initial block came out of nowhere. Ban is likely to be related to the verification phone number I used._ 

## Answer honestly. Check accordingly to your situation.

- [ ] I had prior rule violations on Instagram, specifically:
- [ ] I have admitted the use of InstaGrabber on Instagram.
- [x] I have admitted the use of InstaGrabber to a friend who uses Instagram _but my account is not known to them._ 
- [ ] I have modified the source code of the app that I use, other than what is present in this repo. 

## Describe your case

I have created this account within Instagrabber itself. I have used it to follow people but not to actively produce content or be followed myself.

## Provide your communication with Instagram
One day, Instagrabber would no longer load any data. I then tried logging back in and Instagram said that they had noticed unusual behaviour. I had to verify that everything is legit by solving a captcha, entering a mobile phone number and verifying with a code they sent me to that number. For that purpose, I used the service quackr.io.
Instagram told me, I should get back in 48h, when they have reviewed my block. Three days later, when trying to log in, I am notified that my account was closed due to violating the terms of service.

**Comment by austinhuang0131** [comment]
I guess linking a GitHub issue template doesn't work...

I'd say the actual ban is caused by you using a burner, *never* try to play burner tricks on platforms that deny rights to use proxy.

You did say that you in fact registered the account in the app itself, so I assume you never used it outside the app (prior to ban), which means Instagram does not have tracking data of you (after all they track your scrolls), and by that way Instagram has reasonable suspicions to think you're a bot...

**Comment by 0nse** [comment]
Yeah, I'd say using the burner was the main mistake.

You are right, I have never used that account outside of Instagrabber. However, I followed people so (and a few random ones followed me back), so it must have looked like it was all automated. It might be a good idea to use the real app (or Web app at least) from time to time.

**Comment by austinhuang0131** [comment]
the moral of this story is "if you don't engage posts and only follow people, you're a bot"

**Comment by ovz93br43v7** [comment]
> the moral of this story is "if you don't engage with posts and only follow people, you're a bot"

It really like this? I just watch some pictures from youtubers, through your app. (thanks for providing this app!)
But I have also the problem that after a certain time I get "error loading profile". 

What is your experience with this, do I have to post / like just once or constantly to not be banned?
Does your app support that I post / like through your app?

**Comment by austinhuang0131** [comment]
> It really like this?

Yes.

> What is your experience with this, do I have to post / like just once or constantly to not be banned?

I don't know. I myself have an account that's already some years old, I assume they have some sort of reputation point system... Like if your account is old enough then they won't think you're a bot again. But if you're quite new, they can.

> Does your app support that I post / like through your app?

You can like stuff, yes.
