### ISSUE TITLE
[BUG] Crash clicking two accounts at the same time

### ISSUE THREAD

**Issue by yant0** [austinhuang0131/barinsta#1402]
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Clicking on two accounts at the same time result in crash

## Steps

1. Open Profile
2. Expand followed/followers
3. Open two accounts in the same time

## Environment

 - Device:  asus zenfone maxprom1
 - Android version: 9 stock

**Comment by ammargitham** [comment]
Fixed in https://github.com/austinhuang0131/barinsta/pull/1542
