### ISSUE TITLE
[FTR] sort posts accending by time in layout options

### ISSUE THREAD

**Issue by metemaddar** [austinhuang0131/barinsta#1407]
Hello all. Thanks for all ❤.
Some instagram accounts are reach tutorials which mostly are in series. So I would like to see the first posts first.
I would like to have option to sort posts accending by time. Maybe this option can go to layout options of page.

**Comment by austinhuang0131** [comment]
Instagram sorts all posts in descending time order, then splits them into pages (30 posts each), therefore pages are in descending order. The app cannot fetch all pages immediately as that would possibly lead to a ban. Otherwise it may cause UX confusion
