### ISSUE TITLE
[FTR] add optional skip button when asking where to save Downloads in first start

### ISSUE THREAD

**Issue by Megver83** [austinhuang0131/barinsta#1430]
**Is your feature request related to a problem? Please describe.**
In my specific case, I've a broken internal memory, so when trying to select a folder I get and error and cannot use the app as before, when it didn't ask to select a download folder mandatorily. However others might face similar (non-barinsta related) issues to wish a skip button in this part, or simply want to choose it later.

**Describe the solution you'd like**
As the title says, add a skip button, use a default download folder if skipped

**Comment by austinhuang0131** [comment]
Barinsta can't use a default folder if you have not grant it permission to access that folder through the picker.
