### ISSUE TITLE
[BUG] Won't delete account login data

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1433]
This bug seems to be in Barinsta for quite some time (since I started using it, definitely before the SAF migration) and is in the latest version too.

If you go and delete your account(s) and even uninstall the app, if you then reinstall the app again, it will still remember the previous accounts (which I deleted).

I'm running Android 9 on Samsung Galaxy J7.

If you need any more info from me, feel free to ask. And I would be glad if you could provide me with some instructions how to clean the data manually. Thanks

**Comment by austinhuang0131** [comment]
"Clear data" on my phone does work (deletes accounts and favourites) so uninstall should also work?

**Comment by Martin5001** [comment]
So I now tried clearing the data and at first it seemed to work (the accouts were removed), but then I uninstalled Barinsta and reinstalled it again and after startup, the accounts showed there agan. (It also displayed the "Thanks for updating Barinsta" message as if I just updated.) So clearly there must be some leftovers somewhere.

**Comment by austinhuang0131** [comment]
Okay, it does seem like Google Drive backs up every app's settings so I'll disable that

**Comment by austinhuang0131** [comment]
...or not? I mean people who actually care about privacy would have GMS uninstalled in some way... I could add `clientSideEncryption` as a flag

**Comment by Martin5001** [comment]
> ...or not? I mean people who actually care about privacy would have GMS uninstalled in some way... I could add `clientSideEncryption` as a flag

I personally use Barinsta not for privacy, but to save storage on my device. (Plus the download feature comes in handy occasionally.) I think it would be good to backup the settings, but exclude the login data, if that's possible.

**Comment by austinhuang0131** [comment]
That's not possible with current setup. I'll add encryption.
