### ISSUE TITLE
Error rate limited

### ISSUE THREAD

**Issue by rancidfrog** [austinhuang0131/barinsta#1438]
I just installed app, and was looking at 1 profile and already app is restricted.
![](https://i.imgur.com/ZJiHOhx.jpg)
This should not happen, as picuki storysavernet and other online sites never restrict ips, even after downloading tens of pictures/videos

Something is being done wrong, making app useless.
As I did not even use app for 5minutes and already being blocked.

**Comment by austinhuang0131** [comment]
> This should not happen, as picuki storysavernet and other online sites never restrict ips, even after downloading tens of pictures/videos

Because the websites themselves, not you, are requesting Instagram directly

Again, https://redd.it/msxlko

We're long aware of this but there's practically nothing we can do.
