### ISSUE TITLE
[FTR] Add Copy option to error dialogs

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1440]
Currently when there's an error dialog with details (like Java exceptions etc.), I cannot copy the log from that dialog to easily send it to you. Instead I have to take a screenshot. Please either add a Copy button next to the Ok button, or make the dialog content selectable for copying.

(This seems to be some other error dialog than Sentry, it shows even with Sentry disabled.)

**Comment by austinhuang0131** [comment]
`sentry_block`?

**Comment by Martin5001** [comment]
> `sentry_block`?

Don't know what that is. I'll get you a screenshot later (for some reason GitHub image uploading stopped working on mobile so I'll need to get to my PC).

**Comment by Martin5001** [comment]
It´s this dialog
![Screenshot_20210620-203240_Barinsta](https://user-images.githubusercontent.com/35201200/122871322-1db11400-d32f-11eb-92e6-3822c6beddac.jpg)

**Comment by austinhuang0131** [comment]
how you got to it is actually more important than the error itself
