### ISSUE TITLE
[FTR] Embed music not working

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1441]
There are two ways to add music to your story. One is adding the tag/widget, which Barinsta does support, and the other is when the song name is shown at the very top of the screen with a little soundbar icon, which is ignored by Barinsta.

I don't even know how the second is done in the official app, since I never used that feature, but what I know is that it's not supported in Barinsta (no song displayed at all).

I'll ask the person who posted it how they achieved this to give you more info if needed.

**Comment by austinhuang0131** [comment]
Well, if the story is public, then you can send it?

**Comment by Martin5001** [comment]
I'll try to find a public one and send it in a moment.

**Comment by Martin5001** [comment]
Ok I found this one is public and archived so you should be able to investigate it https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTIwOTYwNjc1NDQ1OTM0?story_media_id=1878171015310479119_1223494147&utm_medium=copy_link

**Comment by Martin5001** [comment]
So they sent me a video of the setup and they actually did use a sticker after all, but moved it out of the view. So maybe Barinsta ignores the sticker when it's not in frame?

**Comment by Martin5001** [comment]
But now I found another story (unfortunately not public), where the music doesn't show at all (and the music tag is in frame). (Also there's a mention button because they tagged someone – so there should be both the tag of the person and the music, but only the person shows up.)

**Comment by Martin5001** [comment]
It doesn't require me to have Spotify installed for the link to show, does it?

**Comment by austinhuang0131** [comment]
The specific ID you gave, `1878171015310479119_1223494147`, does work properly on Barinsta (and on browser) and has a visible music sticker ("I Like It").

Spotify/Soundcloud/Shazam are not actually music stickers, so they won't actually play.

**Comment by Martin5001** [comment]
I see. So I confused two different features. Thanks for explaining that.
