### ISSUE TITLE
[BUG] Cannot register a new account: dropbox of age not working

### ISSUE THREAD

**Issue by raffaem** [austinhuang0131/barinsta#1442]
- [X] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [NO] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq) -> The link returns 404 error

## Steps

I cannot register a new account. When Instagram asks for my date of birth, the dropdown menu does not work.

In the official app, selecting for example "day" will open a popup with all the numbers from 1 to 31. This popup does not open up on Barinsta and so it's impossible to insert the birthday.

## Environment

 - Device: CalyxOS
 - Android version: 11

**Comment by austinhuang0131** [comment]
Update your WebView.

**Comment by raffaem** [comment]
What does it mean update your WebView?

**Comment by austinhuang0131** [comment]
You need to update your WebView, which is either [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) or [Bromite SystemWebView](https://github.com/bromite/bromite/wiki/Installing-SystemWebView).
