### ISSUE TITLE
[BUG] Crashes when logged into account (backup disabled)

### ISSUE THREAD

**Issue by FOSS-Love** [austinhuang0131/barinsta#1449]
- my app is at 19.2.3
- everythings fine without account but when tries to log in it crashes.

**Comment by austinhuang0131** [comment]
crash dump?

**Comment by FOSS-Love** [comment]
The app doesn't report anything the app just doesnt open,

**Comment by FOSS-Love** [comment]
To recreate the bug disable auto backup and add account and app crashes, and if auto backup is enabled everythings working smooth as butter

**Comment by austinhuang0131** [comment]
https://github.com/austinhuang0131/barinsta/commit/ac4bb2e027b6de9136c78cd2e5356b9f3e38203a maybe?
