### ISSUE TITLE
[BUG] Selecting Downloads as Barinsta folder gives error

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1459]
If I select the "Downloads" entry in Android filepicker (leading to Internal storage - downloads), I get an error. But if I go to the same path manually from the Internal storage menu entry ("Galaxy J7"), it works.
![Screenshot_20210620-203307_Files](https://user-images.githubusercontent.com/35201200/122871980-12aab380-d330-11eb-9dd2-4b5270865f5f.jpg)

![Screenshot_20210620-203240_Barinsta](https://user-images.githubusercontent.com/35201200/122871928-00307a00-d330-11eb-8f55-db1058eef6b3.jpg)
![Screenshot_20210620-203243_Barinsta](https://user-images.githubusercontent.com/35201200/122871938-032b6a80-d330-11eb-98a6-2f9391c364d5.jpg)
Android 9 Samsung Galaxy J7

**Comment by austinhuang0131** [comment]
escaped by https://github.com/austinhuang0131/barinsta/commit/d031998123ef69f7b0bc0c048f0f3f120c0dc63e
