### ISSUE TITLE
[FTR] Contain all Barinsta data in a main folder

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1460]
Currently Barinsta temporary and download files are stored directly to the user specified folder. But if user selects for example the Downloads folder, there may already be some other files. So to prevent mixing and to make everything nice and tidy, I think Barinsta should create a containing folder (named Barinsta) and then put all the other data within this folder. So change the structure from "Some folder – data" to "Some folder – Barinsta – data".

**Comment by ammargitham** [comment]
The idea is that the user should create the folder they want barinsta files in and choose that folder.
