### ISSUE TITLE
[BUG] Stories show blank

### ISSUE THREAD

**Issue by Martin5001** [austinhuang0131/barinsta#1496]
If you want to view a story, you'll see the small preview at the bottom, but the main view won't show. Also swiping to see next stopped working. No loading, just blank.
Build 19d3434 Android 9

**Comment by austinhuang0131** [comment]
need example

**Comment by Martin5001** [comment]
Ok, this account is public https://instagram.com/marjanakosjuk – so far it seems all stories for this (but also every other account) are affected (so it doesn't seem to be account specific, at least from what I can see, but here's your example). Feel free to ask if you need any more info.

**Comment by Martin5001** [comment]
@austinhuang0131 This may be important info: tapping a story for this account even causes the app to crash https://instagram.com/graphicdesign.world
(Crash dump when I get to my PC later if needed)

**Comment by austinhuang0131** [comment]
okay, i did see the crash now, will try to fix
