### ISSUE TITLE
[BUG] App crashing when it is opened (DateTimeFormatter?)

### ISSUE THREAD

**Issue by Raniconduh** [austinhuang0131/barinsta#1499]
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq.html).

The app crashes immediately when it is opened.

## Steps

1. Open app
2. App crashes

## Environment

 - Device: LG G7 ThinQ
 - Android version: 8.0.0

**Comment by austinhuang0131** [comment]
crash dump?

**Comment by Raniconduh** [comment]
How would I get a crash dump?

**Comment by austinhuang0131** [comment]
The app should give you a dialog to report crash, or it will say it has been reported to Sentry, but either way it will give you something

**Comment by Raniconduh** [comment]
I don't get anything of the sort. I open the app and android immediately tells me `Barinsta has stopped`. If I open the app multiple times, I only get `Barinsta keeps stopping` with the only option being to `Close app`

**Comment by austinhuang0131** [comment]
Okay, well, the problem is it has not been occurring for others and I must get the crash dump to fix it, so either try with [nightlies](https://github.com/austinhuang0131/barinsta/actions/workflows/github_nightly_release.yml) if you're on the GitHub version, or wait for someone else to call it in.

**Comment by austinhuang0131** [comment]
Can you logcat?

**Comment by austinhuang0131** [comment]
By https://t.me/barinsta_app/22067 I'm told that clearing data does fix it, but I still don't have a cause

**Comment by austinhuang0131** [comment]
@HelmetOwl Interesting. It seems like you got the answer and I'll see what I can do.

In #1309 we switched to LocalDateTime, which [has no timezone](https://stackoverflow.com/questions/25561377/format-localdatetime-with-timezone-in-java8) (since it's meant to always be at your system timezone). Sure, I could change it to ZonedDateTime, but is it a necessity?
