### ISSUE TITLE
F-DROID Support

### ISSUE THREAD

**Issue by dm17** [austinhuang0131/barinsta#153]
In F-DROID you said:
"Bug fixes, see GitHub. This is the FINAL regular release for the old UI/codebase."

Does that mean that we should not be expecting updates in F-DROID anymore - or that it is deprecated from that install location?
Thanks!

**Comment by austinhuang0131** [comment]
"for the old"

**Comment by dm17** [comment]
@austinhuang0131 sorry but I don't know what the "old UI" or "old codebase" is... But it sounds like it doesn't mean what I thought.
Thanks.

**Comment by austinhuang0131** [comment]
We're going through a redesign/rebrand and I'm basically ending the previous design.

It's sorta deprecated, but will only be properly deprecated when we release the redesign.

**Comment by dm17** [comment]
> We're going through a redesign/rebrand and I'm basically ending the previous design.
> 
> It's sorta deprecated, but will only be properly deprecated when we release the redesign.

OK, so people who have the current app on F-DROID can expect it to continue to update into the new app / design? Or should they watch out for the app to be deprecated & look for the redesigned app under another name on F-DROID later?
Thanks.

**Comment by austinhuang0131** [comment]
The redesigned app will be under the same package name `me.austinhuang.instagrabber`, it's just we're changing name and stuff

You'll be updated on F-Droid
