### ISSUE TITLE
[BUG] Downloaded media go into a "Downloads" subfolder

### ISSUE THREAD

**Issue by arthurjosse** [austinhuang0131/barinsta#1549]
Since updating the app from v. 19.2.2 to v. 19.2.3, downloaded posts and stories goes to a "Downloads" subfolder instead of directly to the parent folder that I've set.   

## Steps

1. Set MyFolder as Barinsta downloads folder
2. Download a post in Barinsta
3. The downloaded post appears in MyFolder/Downloads/ instead of MyFolder/

## Environment

 - Android version: 11
 - Barinsta installed through F-Droid

**Comment by ammargitham** [comment]
The folder selected for Barinsta acts as the root for all other sub directories, one of which is the Downloads folder.

**Comment by arthurjosse** [comment]
hmmm not clear. It's something new in 19.2.3 then? If so, why? In 19.2.2 downloading worked as intended (no subfolder).

**Comment by ammargitham** [comment]
Due to new Android apis. Barinsta can only have access to 1 folder and can create files/folder in that folder only. So we need to organise everything inside that folder for other stuffs as well.

**Comment by arthurjosse** [comment]
Ah, OK. Thanks.
