### ISSUE TITLE
[BUG] Profile fragment: Refresh to top after viewing post

### ISSUE THREAD

**Issue by ammargitham** [austinhuang0131/barinsta#1568]
From https://redd.it/obsl0n

> This bug began 2 updates ago I think. After viewing a post and hitting back (either the Android nav or the in-app arrow up top) it will automatically scroll all of the way back to the top of the feed or the profile I was checking out.
> 
> Not sure if it's try relevant, but around the same time this issue started, I noticed loading times for images when scrolling down got pretty long.

**Comment by ammargitham** [comment]
I can't seem to reproduce this issue on my device. Maybe the profile fragment changes after 19.2.3 fixed it.

**Comment by FireMasterK** [comment]
I'm able to reproduce this on 19.2.3.

**Comment by austinhuang0131** [comment]
we said "after 19.2.3"

**Comment by FireMasterK** [comment]
Gotcha! My bad.
