### ISSUE TITLE
[FTR] Add Saved to the More tab

### ISSUE THREAD

**Issue by yant0** [austinhuang0131/barinsta#1587]
**Is your feature request related to a problem? Please describe.**
Instagram app have the Saved at hamburger menu at the account tab, muscle memory

**Describe the solution you'd like**
Add Saved to the More tab

**Comment by austinhuang0131** [comment]
By the same argument I had to add other menus there too?

The deal with Saved being at profile is to make it more convenient, this remains the Developers' opinion, case closed
