### ISSUE TITLE
[FTR][UX] pull up gesture

### ISSUE THREAD

**Issue by ildar** [austinhuang0131/barinsta#160]
for "Back" action.

I actually never installed original app on my phone so i may be wrong. But i think that the gesture would be helpful: tapping Back is too far.

**Comment by ammargitham** [comment]
You mean scroll to top on back?

**Comment by ildar** [comment]
No, sorry.

It's in an article view where gesture left/ right navigates prev/next. Then
adding gesture bottom to top would be convenient.

**Comment by HristianIliev** [comment]
@ildar  Can you please give more context on what exactly is your proposal?

**Comment by ildar** [comment]
It works so in many apps.
It's in an article view where gesture left/ right navigates to prev/next
(article). Then adding a new gesture "drag the picture bottom to top" would
be convenient. The gesture action is "Back".
If my description is not clear then take a look in an app. The one I know
is Telegram (when viewing pictures).

**Comment by ammargitham** [comment]
I will be attempting to add this in the feed view revamp I am working on.

**Comment by ammargitham** [comment]
This has been added in v19.0.0.
