### ISSUE TITLE
[FTR] add warning before sharing content from private account

### ISSUE THREAD

**Issue by yant0** [austinhuang0131/barinsta#1605]
**Is your feature request related to a problem? Please describe.**
No warning when sending posts from private accounts

**Describe the solution you'd like**
- a warning they're about to share private account content
- highlight people who followed the account

**Additional context**
Instagram's warning before sharing content from private account

**Comment by austinhuang0131** [comment]
> a warning they're about to share private account content

Yeah, I'll make a toast.

> highlight people who followed the account

That's not possible.
