### ISSUE TITLE
Select directory not category from storage. Then crash

### ISSUE THREAD

**Issue by anoduck** [austinhuang0131/barinsta#1617]
Updated to 19.2.3—fdroid and upon opening app, asked to select directory for downloads. When directory is selected and permission granted, message pops up stating to select directory not category from sidebar. Then app closes and/or crashes. 

Enjoyed using app very much, way better than Instagram app. 

Phone model is a Kyocera duraforce pro E6910
OS. Version Android 10

**Comment by austinhuang0131** [comment]
> When directory is selected and permission granted, message pops up stating to select directory not category from sidebar.

You should select from internal storage instead of a third-party file explorer. Next version would indicate it better.

> Then app closes and/or crashes.

Need crash dump

**Comment by anoduck** [comment]
I have no idea how that worked, but it did and the issue is resolved. Going ahead and closing it out, as I do not know how to reproduce the problem.
