### ISSUE TITLE
[FTR] Direct Messages issue

### ISSUE THREAD

**Issue by DomenicoakaTDG** [austinhuang0131/barinsta#1633]
## Intro

Version of Barinsta: 19.2.3.-github_release (64). I understand that any versions before that is not supported. I have read [the FAQ] (https://barinsta.austinhuang.me/en/latest/faq.html).

## Problem

When I want to send a Direct Message to a profile "extracted" from an hashtag but instead I am redirected to the list of DM I have already sent from my profile. No conversion created.

## Steps

1. Search for an hashtag
2. "Enter" the hashtag
3. Select a profile
4. "Enter" the profile
5. Click on Send
6. Redirected instead to the Direct Messages of MY profile already delivered instead of the new conversation that should have been created.

## Environment

 - Device: Sony Xperia XZ Premium G8141
 - Android version: 9

**Comment by austinhuang0131** [comment]
Not reproducible on master, assumed fixed.
