### ISSUE TITLE
[BUG] No application found to open URLs

### ISSUE THREAD

**Issue by DomenicoakaTDG** [austinhuang0131/barinsta#1642]
## Version of the app ↓

19.2.4-github_release (65)

## Problem

Whenever I want to open a link to a web page from Barinsta it tells me that I don't have an associated app that would allow me to open them. That is not true because I have set, as you can see in the screenshots that I will attach, Vivaldi as the default browser for opening links and from other applications this association works.

## Steps

1. Clink on a link in a DMs
2. Can't open the link in any way and it returns this error message: *No application found to open URLs*

## Environment

 - Device: Sony Xperia XZ Premium (G8141)
 - Android version: 9

![#2](https://user-images.githubusercontent.com/77741077/125415458-355e92c5-aabd-4796-9512-581028ee248a.png)

![#1](https://user-images.githubusercontent.com/77741077/125415462-7814bd04-a279-442b-8e71-71e11ac60ac7.png)

**Comment by ammargitham** [comment]
Seems to be a change in the startActivity behavior since target api level 30.

**Comment by DomenicoakaTDG** [comment]
Hi ammargitham, I guess... thanks for the suggestion! 🤔

But you didn't tell me how can I fix the problem, is there any workaround for this?😅

**Comment by ammargitham** [comment]
You don't have to do anything. It was a bug/change in api which has been resolved in code. You will have to wait for the next release. Or tomorrow's nightly build.

**Comment by DomenicoakaTDG** [comment]
Thanks for the clarification. I learned something today!

Therefore I will wait patiently, have a nice day.
