### ISSUE TITLE
challenge_required

### ISSUE THREAD

**Issue by Archgod-Git** [austinhuang0131/barinsta#1643]
Trying to access my DMs, Feed and Profile just leaves me with a blank page and a small gray prompt in the bottom-middle that says "challenge_required". Searching for other users seems to work fine after I cleared my data and their profiles show up too so I'm not sure how to fix this. (Latest arm64v8a version from github releases.)

**Comment by nityy** [comment]
"challenge_required" means you need to login instagram on web or their app and follow their instructions.

**Comment by ammargitham** [comment]
@Archgod-Git , @nityy Is correct
