### ISSUE TITLE
Login Failure (Error: Not Found) [BUG]

### ISSUE THREAD

**Issue by jasonjaeger11** [austinhuang0131/barinsta#1645]
- [ yes] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [ yes] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq.html).

 Unable to log in for a certain account which still can be used on Original App. Other accounts working fine.
![image](https://user-images.githubusercontent.com/87370381/125444443-a79af64e-f290-45c2-83a1-0715b3326ee4.jpeg)

## Environment

 - Device:  Redmi Note 5 
 - Android version: 7

**Comment by austinhuang0131** [comment]
Try:

1. Log into Barinsta on a browser on a computer
2. Right click => "Inspect" or "Inspect Element" somewhere on the page to open the dev panel.
3. For Chrome/Chromium, go to the "Application" tab, then "Cookies" (open drawer if necessary), then "https://www.instagram.com". For Safari, go to the "Storage" tab, then "Cookies - https://www.instagram.com".
4. See if "ds_user_id" exists and is a number.

**Comment by jasonjaeger11** [comment]
yes, the ds_user_id exists and its a number.

**Comment by jasonjaeger11** [comment]
> yes, the ds_user_id exists and its a number.

**Comment by jasonjaeger11** [comment]
> This is more likely an Instagram issue.
> 
> Try:
> 
> 1. Log into Instagram on a computer
> 2. Right click => "Inspect" or "Inspect Element" somewhere on the page to open the dev panel.
> 3. For Chrome/Chromium, go to the "Application" tab, then "Cookies" (open drawer if necessary), then "https://www.instagram.com". For Safari, go to the "Storage" tab, then "Cookies - https://www.instagram.com".
> 4. See if "ds_user_id" exists and is a number.

yes, the ds_user_id exists and its a number.

**Comment by austinhuang0131** [comment]
You already responded once, I get 1 email per response so please don't repeat them

then I don't know why one specific account can't work but other accounts do

**Comment by jasonjaeger11** [comment]
Ok, sorry
