### ISSUE TITLE
[BUG] "Backup and resore & About" are unclickable

### ISSUE THREAD

**Issue by FOSS-Love** [austinhuang0131/barinsta#1648]
- [x] My app is *at least* at the current release version. I understand that any versions before that is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq.html).

Backup and restore and about section has no action on click.

**Comment by austinhuang0131** [comment]
fixed in https://github.com/austinhuang0131/barinsta/commit/5b9edcfa8b67d1a1bb9a532eac2473da47d44318
