### ISSUE TITLE
[BUG] Non-authenticated likes crashes the app

### ISSUE THREAD

**Issue by andersonvom** [austinhuang0131/barinsta#167]
- [✓] My app is on the latest version. I understand that any other version is not supported.
- [✓] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

Liking a post crashes the app if you're not logged in.

## Steps

1. Make sure you're not logged in
2. View a public post
3. Click the `Like` button

**Expected behavior**: nothing should happen
**Actual behavior**: the app crashes.

## Environment

 - Device: Pixel 3a XL
 - Android version: 10

**Comment by austinhuang0131** [comment]
(I saw PR first then this)

Can't reproduce, you shouldn't be able to see like/bookmark buttons when you're not logged in...

How did you bring up the post?

**Comment by austinhuang0131** [comment]
just realized you meant v19.0-a1

will `GONE` the like buttons instead

**Comment by andersonvom** [comment]
Oh, yeah, I see the issue on master, but if the buttons will be gone, then we can probably close this issue then. :)
As you mentioned in the PR, it won't actually cause any issues, so probably still valid.
