### ISSUE TITLE
[FTR] Add a DM-Only mode

### ISSUE THREAD

**Issue by Stig124** [austinhuang0131/barinsta#1680]
**Is your feature request related to a problem? Please describe.**

I mainly use instagram for DM purposes, so 50+% of the app is absolutly useless for me

**Describe the solution you'd like**

Add a switch in the settings to disable everything except DMs

**Comment by austinhuang0131** [comment]
Except DMs have post, story, and profile messages; then we need to keep profile, hashtag, location, comments, stories; then you'll realize the saving is really marginal

Deemed edge case
