### ISSUE TITLE
[FTR] sort photos on a profile by oldest 1st

### ISSUE THREAD

**Issue by Goldmaster** [austinhuang0131/barinsta#1683]
**Is your feature request related to a problem? Please describe.**
On Instagram, you can only view photos by newest 1st and so if a profile has loads of photos, it can take a while to scroll down and view older photos.

**Describe the solution you'd like**
when viewing a profile, or your own, you can tap the 3 dots top right and there could be a button that says `Oldest 1st` to view oldest 1st. Then the button would change to say newest 1st for when the user wants to switch back to `Newest 1st
`.
**Additional context**
There could be bracket text saying what the user is currently viewing. Such as `(currently viewing oldest/newest 1st)`

**Comment by austinhuang0131** [comment]
All posts are paginated, so I have to fetch starting from the first (newest) page, so not possible

**Comment by Goldmaster** [comment]
How do you mean have to fetch starting from the first (newest) page? As they are paginated?

**Comment by austinhuang0131** [comment]
> All posts are paginated

So because I don't know where the last page is, I have to fetch from the first (newest) page, then in each page I'm given how to access the next page

I can't fetch all the pages then sort them by old-to-new because that'd risk a ban
