### ISSUE TITLE
[BUG] Public stories in incognito mode are not shown

### ISSUE THREAD

**Issue by rgabbo** [austinhuang0131/barinsta#169]
- [X] My app is on the latest version. I understand that any other version is not supported.
- [X] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

## Steps

1. Open a public profile that has one or more active stories
2. Try to reproduce it without login to any account
3. Story is not reproduced

## Environment

- Device: Cat S52
- Android version: 9

**Comment by austinhuang0131** [comment]
https://barinsta.readthedocs.io/en/latest/faq/#story (It's on the new FAQ which isn't released yet so I don't blame you for not reading it prior)

Related to #132
