### ISSUE TITLE
[BUG] Thai comments can not be translated

### ISSUE THREAD

**Issue by Androz2091** [austinhuang0131/barinsta#1716]
Steps to reproduce:

1) Go to https://instagram.com/uninspiredbycurrentevents, there are a lot of Thai comments

2) Try to translate Thai comment, it will show "Une erreur s'est produite !!"

 ![example](https://i.goopics.net/o1lZL.jpg)

**Comment by austinhuang0131** [comment]
Instagram seems to return empty string when trying to translate Thai, and `null` when trying to translate only emojis

```json
{
  "translation": "",
  "status": "ok"
}
```

That post does have an English comment, whose translation works, so that's upstream

**Comment by Androz2091** [comment]
Hmm, so you are saying that you won't fix the bug because it's on instagram side right?

**Comment by austinhuang0131** [comment]
yeah
