### ISSUE TITLE
A dedicated feed option for favorited pages.

### ISSUE THREAD

**Issue by lijovklm** [austinhuang0131/barinsta#1718]
Hey, thanks for making this excellent app.

I was thing of having a feed just as the regular feed, just for the favorited pages, individual accounts etc.
This should be present even in private mode as we can favorite channels without logging in.

**Describe the solution you'd like**
A feed of favorited pages, like the regular insta feed, may be sorted about most recent.

Please try to include this feature if possible. Thanks again.

**Comment by austinhuang0131** [comment]
Duplicate of #24
