### ISSUE TITLE
[FTR] add feature graphic

### ISSUE THREAD

**Issue by iNtEgraIR2021** [austinhuang0131/barinsta#1729]
Hi 👋🏼 

I just created a [**feature graphic**](https://support.google.com/googleplay/android-developer/answer/9866151?hl=en#zippy=%2Cfeature-graphic) for barinsta using Gimp. This seems to be a missing of the apps [**fastlane structure**](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure).

![barinsta_feature-graphic](https://user-images.githubusercontent.com/80395360/126787516-5678f8b7-d194-4a6b-85d6-7cc6e8b343c4.png)

**Since F-droid 1.6 this is part of the required criteria for apps to be featured on the 'latest' tab of the f-droid app store.** [-> source](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#latest-tab-criteria)

Please also see here for further information regarding the fastlane structure: <https://gitlab.com/-/snippets/1895688>

### 📁 Attachments

[barinsta_feature-graphic.zip](https://github.com/austinhuang0131/barinsta/files/6869001/barinsta_feature-graphic.zip) -> contains the **Gimp .xcf file** -> for possible further modifications

[barinsta_feature-graphic](https://user-images.githubusercontent.com/80395360/126787516-5678f8b7-d194-4a6b-85d6-7cc6e8b343c4.png)

**Comment by austinhuang0131** [comment]
> at least one graphic (screenshot **or** a feature graphic)

Emphasis "or", so it's not required. Plus it's been there since 2019 and I'm sure I have seen Barinsta in the Latest section.

I would rather have someone to draw a proper graphic instead of just putting the logo on a banner.

**Comment by iNtEgraIR2021** [comment]
Here are all assets bundled: the **source** (-> launcher icon from README.md), the **.xcf** file and the feature graphic as a **.png** file.

➡️  [barinsta_feature-graphic__all-assets.zip](https://github.com/austinhuang0131/barinsta/files/6869059/barinsta_feature-graphic__all-assets.zip) ⬅️

**Comment by iNtEgraIR2021** [comment]
ah well that was fast. ok. As your not interested.

Since no one opened a issue on this since 2019 you'd might be design it yourself. Sorry but not sorry. One hand you (seem) to be urgently looking for help but on the other you dismissed literally 4mins after I tried to help.

You literally just closed this issue right away without me even having the chance to do change anything.

**Comment by iNtEgraIR2021** [comment]
| I would rather have someone to draw a proper graphic instead of just putting the logo on a banner.

Ok. That's your opinion. So better no graphic than one that doesn't fit your elite criteria.

Sorry but I got a 9 to 5 job to do I won't waste more time people being to haughty to express them selves in a polite way.
Go back to your friends a find someone who designs it the way as you want it to be.
