### ISSUE TITLE
[BUG] BarInsta (new alpha release) does not load DM posts and/or videos/photos

### ISSUE THREAD

**Issue by GoDzM4TT3O** [austinhuang0131/barinsta#175]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

When going into my DMs, and opening either a group or a private chat, BarInsta does not show shared posts, nor photos and videos sent.

## Steps

1. Open BarInsta (must be logged in)
2. Click on `DM`
3. Open a private chat with a user or a group
4. If you sent any media (photos, videos, posts), you will not be able to see them. They do not load

## Environment

 - Device: Samsung Galaxy A50
 - Android version: 10

## Additional info

I do not have a log to share because I can't find the option to show the log

I should add that Instagrabber, however, works fine. This issue is only present in BarInsta.

**Comment by ammargitham** [comment]
Fixed in https://github.com/austinhuang0131/barinsta/commit/b5e66e35bf1501c0c4aad91bff82e037ca14bf03
