### ISSUE TITLE
[FTR] Add the 'Swipe up' Functionality

### ISSUE THREAD

**Issue by canbarelycode** [austinhuang0131/barinsta#1753]
I'm fairly certain that this feature was already implemented in older versions but since the last update it seems to be gone.

I'ld appreciate it if the 'Swipe up' functionality will be implemented so that I can access the links shared in stories just like I can access the mentions or the other gimmicks in the stories.

Thank you very much for your work on this amazing project. Barinsta really came a long way in the last months.

**Comment by austinhuang0131** [comment]
[It is there.](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awais/instagrabber/fragments/StoryViewerFragment.kt#L839) They're now merged into the sticker button.

**Comment by canbarelycode** [comment]
Hi,

I assumed that it is supposed to be in the sticker button, but it's just not available.

The attached screenshot is just for one example I have the same problem with every single 'swipe up' story.

so maybe I should have called it a bug report instead of a feature request.

25.07.2021 15:44:02 Austin Huang ***@***.***>:

**Comment by austinhuang0131** [comment]
There's no attachment but I do see the issue now
