### ISSUE TITLE
[BUG] PostViewFragment is only showing low-resolution squared thumbnails

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/barinsta#215]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

## Steps

1. Access post from profile
2. Instead of seeing properly-sized images i see the squared thumbnails

## Environment

 - Device: irrelevant
 - Android version: 9

**Comment by ammargitham** [comment]
The current PostViewFragment is getting replaced. So I will check this out in the new one.

**Comment by austinhuang0131** [comment]
seems fixed

**Comment by austinhuang0131** [comment]
not fixed on story linked post, sus
