### ISSUE TITLE
[Privacy Issue] Crash reports mention emails which could potentially be a privacy issues

### ISSUE THREAD

**Issue by PsyGik** [austinhuang0131/barinsta#223]
I was going through the crash reports to see if I can contribute and observed that the e-mails of users reporting the crash is visible. This could lead to a potential privacy Issue.

Unless I'm mistaken and my dumb self assumed it to be the end users email then feel free to close this thread.

**Comment by austinhuang0131** [comment]
Bot doesn't detech questions (only bugs and enhancement labels).

* Yes, it is end user email
* It's written in privacy policy ([Old](https://instagrabber.austinhuang.me/disclosure) / [New](https://barinsta.austinhuang.me/en/latest/privacy/#crash-dumps))
* They can ask me to redact it (`im @ my domain`)
* v19.0 and forward will have [this warning](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awaisomereport/CrashReporter.java#L73) before sending crash report

**Comment by PsyGik** [comment]
Ah I see. Thanks for the clarification! Closing this thread.
