### ISSUE TITLE
[FTR] A couple of suggestions

### ISSUE THREAD

**Issue by Yakabuff** [austinhuang0131/barinsta#228]
1. Would it be possible to add a panel where it allows you to see all images you download sorted by the user?  Utilizing a DB to keep track of images downloaded would be much cleaner compared to making a new folder for every user.
2. Prevent downloading the same image twice to save storage space
3. Skip stories to next user by swiping. Skip to next photo by tapping

**Comment by ammargitham** [comment]
Hey, thanks for the suggestions. Will keep in mind as we update the app.

**Comment by austinhuang0131** [comment]
1. We rely on file names since we cannot easily track renamed/deleted files otherwise.
2. It'll just overwrite the file...
3. Implemented in another form in v19.0.0
