### ISSUE TITLE
[BUG] Downloaded images corrupted

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#235]
Occasionally, both InstaGrabber (v18.3) and Barinsta (v19.0-a2) download corrupted / incomplete (?) files and always from the same posts. e.g. I get a corrupt file from this post every time: https://instagram.com/p/CFvFbnYhf_g

OS: Android 10.

**Comment by alin-1** [comment]
Occasionally, both InstaGrabber and Barinsta (latest versions) download corrupted / incomplete (?) files and always from the same posts. e.g. these apps download a corrupt file from these posts on every try: 
https://instagram.com/p/CFvFbnYhf_g
https://instagram.com/p/CGGG0MJB7AS

**Comment by austinhuang0131** [comment]
related #215

**Comment by Tech-Geek97** [comment]
I am also having the same bug.

**Comment by MrDoritos** [comment]
Same here

**Comment by austinhuang0131** [comment]
Maybe it's due to the notification thing, which does take some memory

Considering a "download started..." toast and a "download finished..." notification for the entire queue, not just each picture

**Comment by ranjit0829** [comment]
Hello Austin,

Thank you for this wonderful app. :)
Just worth mentioning, I am able to download the Instagram profile image and the videos but when Download a post or group of post, images get corrupt after download. 

Looking forward for the fix. 

Thanks,
Ranjit

**Comment by austinhuang0131** [comment]
we have added proper rewriting mechanism in #245 so this should no longer be a problem
