### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by modelfe** [austinhuang0131/barinsta#249]
EDIT: sorry forgot to title this: Images not downloading

- [x] My app is on the latest version. I understand that any other version is not supported.

- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

I'm not sure if this is related to [this issue](https://github.com/austinhuang0131/barinsta/issues/235), but all images I try to download from the main instagram timeline and from individual users' pages currently result in images not being downloaded at all. They're just blank image files appearing in my gallery app. Instagram Story images and videos are not affected, and download fine.

## Environment

 - Device: Mi A2
 - Android version: 10

**Comment by austinhuang0131** [comment]
if you know it's a duplicate then you should comment it in the parent issue...

read last comment of #235
