### ISSUE TITLE
[FTR] option to stop video auto buffering 

### ISSUE THREAD

**Issue by Raj9039852537** [austinhuang0131/barinsta#250]
Every time I opened the app there is around 10 MB data usage. I have uninstalled official app for the same reason.

My suggestion is to provide an option which when enabled provide the user an opportunity to disable auto buffering of videos. This will conserve a lot of data. The autoplay videos stop it from playing but it is buffered and use data.

Thanks for the app.

**Comment by austinhuang0131** [comment]
In the new version (#245) you would be able to just use grid view to disable autoplay.

**Comment by Raj9039852537** [comment]
Sure. 
But autoplay is not a problem. The software already have an option to disable autoplay.
The real problem is auto buffering of videos even if autoplay is disabled.

**Comment by ammargitham** [comment]
There will be no data usage/buffering until the thumbnail is clicked in #245
