### ISSUE TITLE
[BUG] Some messages don't disappear (While in anonymous mode) in v19.0.0

### ISSUE THREAD

**Issue by RickyM7** [austinhuang0131/barinsta#257]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

Mentions like "like unsucessfull", "save unsucessfull" do not disappear until you leave the post
## Steps

1. Go to 'any post'
2. Click on 'save, like, etc.'
3. See error

## Environment

 - Device: Xiaomi Redmi Note 4
 - Android version: Miui 11 - Android 7.0

**Comment by austinhuang0131** [comment]
aka I have to hide like/save for anons
