### ISSUE TITLE
One of best Instagram app ever used

### ISSUE THREAD

**Issue by prasumoholkar** [austinhuang0131/barinsta#260]
App is nice, new version 19.0 stable.
Some suggsion for improvement in app and feature request.

1.add favourite button like previous app version has it
2.Add HD photos with maximum resolution for download option.

Thanks in advance.

**Comment by austinhuang0131** [comment]
1. Out of design complications, no.
2. Instagram downscales photos to max 1080x1080 (which is proven by me personally). I mean, you're looking at a mobile app, so Instagram (as a platform) will probably not serve FHD photos. Whatever you're downloading is already of the highest quality the app can get from Instagram.
