### ISSUE TITLE
Most Grabbed Images Don't Work

### ISSUE THREAD

**Issue by dm17** [austinhuang0131/barinsta#262]
Not sure how to debug this. I'm using the latest Instagrabber from F-DROID (it doesn't show up as "barinsta" yet). About half of the downloaded images I get show up as an error message in the Android gallery. As if they're downloaded in an unsupported format or something. Any idea how to debug?
Thanks.

**Comment by austinhuang0131** [comment]
wait for F-Droid to pick up v19.0.0

**Comment by dm17** [comment]
> wait for F-Droid to pick up v19.0.0
> 
> duplicate #235

Great! Oh, so F-DROID is bottlenecking it? Is the code identical on F-DROID and GitHub? Maybe just as safe to get it from GitHub?

**Comment by austinhuang0131** [comment]
read last message of #40 

the code is identical by design, but signed with different keys, so if you get it from F-Droid then you must update it from F-Droid, same applies for GitHub
