### ISSUE TITLE
[BAN] "suspicious" and "unusual" activity on my account

### ISSUE THREAD

**Issue by 0100001001000010** [austinhuang0131/barinsta#263]
I'm not sure that this counts, because I have not received a full-on ban. However, in the past few days I was asked to complete some verification steps twice in order to be allowed to use my account, so I'm concerned that this might become a full on ban in the near future.

A couple days ago, Instagrabber stopped working, reporting failures to load everything. This happened while I was in the middle of actively using Instagrabber. I signed in through the website, and my account was "locked due to suspicious activity", and I was required to verify my email and then change my password in order to actually do anything. After I signed in again on Instagrabber, it worked again.

Today, I tried to use Instagrabber, and it also failed to load everything. I signed in through the website again. This time, they told me that they noticed "unusual" activity on my account and it would be "restricted" for 3 days, but that the restrictions could be lifted early by solving a reCAPTCHA. I did that and now have full access to my account again.

I looked at the login history and found no strange logins to my account, and I rarely post or engage with anything (I pretty much just look at stuff and direct message people) so I find it unlikely that this is related to weird activity, so I think it's more likely that this is caused by this app. Is there a way that I can find out for sure, or could there be something else about my usage that Instagram doesn't like?

**Comment by austinhuang0131** [comment]
Have you *ever* used the official app? What is your usage pattern? ("I rarely post or engage with anything (I pretty much just look at stuff and direct message people)" yeah you might need to casually like some posts idk)

Also refer to #140

**Comment by austinhuang0131** [comment]
closing for stale, please reopen on reply
