### ISSUE TITLE
[FTR] 3 new suggestions

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#275]
1. Instead of that download popup use 2 download buttons: download all and download current (in this order). If the post has just one item the download all button is not displayed. This would be very efficient.

2. Add a link to the username from the header of the Story pages to go to that user's page.

3. When a post is maximized (popup over the app) add the swipe gestures up / down to switch to the next / previous post in line while not leaving the maximized mode.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by ammargitham** [comment]
1. Dialog is shown only for an album post. Otherwise the photo/video is downloaded without prompt.

2. Known issue. Will be fixed.

3. No plans to implement this as of now. Maybe later.
