### ISSUE TITLE
[BUG] Downloads stuck

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#280]
Certain downloads are stuck. The notification remains blocked indefinitely and only a phone restart make them disappear. Please fix this and also add buttons to cancel and restart downloads. A sort of download manager page would be even better.

![stuck](https://user-images.githubusercontent.com/13281020/99245677-a5b8c380-280c-11eb-812d-765b21c7566e.jpg)

- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

## Environment

 - Device: 
 - Android version:

**Comment by ammargitham** [comment]
Can you give more info? Which types of posts? Did your internet connection disconnect in-between? If possible you can reach out via one of the chat groups to share any private links to help us debug.

**Comment by austinhuang0131** [comment]
stale

**Comment by ammargitham** [comment]
Still present: https://t.me/grabber_app/14724

**Comment by Kreuger** [comment]
This has started happening to me again.

**Comment by austinhuang0131** [comment]
stale
