### ISSUE TITLE
[FTR] Username folders now prefix with @

### ISSUE THREAD

**Issue by MrDoritos** [austinhuang0131/barinsta#284]
**Is your feature request related to a problem? Please describe.**
I have hundreds of folders with no @ prefix. I could rename the folders using `rename`, but an @ is redundant nonetheless.
![Screenshot_20201116-085752](https://user-images.githubusercontent.com/36420971/99277736-115b5a80-2826-11eb-9f60-9ac061170f1e.jpg)

**Describe the solution you'd like**
An option in the config to be able to choose between an @ prefix and no @ prefix.

**Additional context**
None.

**Comment by austinhuang0131** [comment]
Pre-v19 it was without the @, but post downloads use ID; Now posts use shortcodes

I can just change [this](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awais/instagrabber/utils/DownloadUtils.java#L278) but I'd prefer more input on this

**Comment by alin-1** [comment]
It would be great without that @ sign. Or at least make it optional.
