### ISSUE TITLE
Russian translation [Q]

### ISSUE THREAD

**Issue by rikishi0071** [austinhuang0131/barinsta#301]
Hi. I'd like to start translating this app to Russian. What should I do? Can you create a language? Can you create an account for me to start translating? Should I write an email to you? Thank you!

**Comment by austinhuang0131** [comment]
I'll just pin this for general guidance...

There are two ways to contribute to translations:

## The online way

1. Go to [our Crowdin project](https://crowdin.com/project/instagrabber).
2. If you do not have an account, you need one.
3. If the language is not there, I need to know. I am open to adding *any* language, just that I need to know them one by one.
4. Once the language is there, you can request membership.
5. You'll get membership whenever I read requests.

* You will get emails on new strings.
* You will be removed from project if you have no substantial contributions for the first month.
* If you contributed the majority of translations in a certain language, you will be credited in your GitHub username.

## The offline way

If you somehow don't agree on Crowdin's terms or privacy (it happens!) then there is an alternative:

1. Download strings.xml and arrays.xml from res/values.
2. Edit the XML files yourself.
3. Send me the files privately through email (NO PULL REQUESTS) at im@austinhuang.me. Include your GitHub username.

* You will not be notified on new strings, so it is your responsibility to check.
* Your translations will still be uploaded to Crowdin.
