### ISSUE TITLE
[BUG] Pressing Followers/Following shows a feedback, bug nothing happens 

### ISSUE THREAD

**Issue by 532910** [austinhuang0131/barinsta#312]
![ScreenRecord-2020-11-20-14-29-07](https://user-images.githubusercontent.com/14617699/99795600-162d5080-2b3d-11eb-9ffc-9fc57d980c40.gif)

**Comment by austinhuang0131** [comment]
Anonymous users can't see followers/following (API restrictions)

in code this has been made clickable only for logged-in users

**Comment by 532910** [comment]
So in the next version it will non be clickable, right?

**Comment by austinhuang0131** [comment]
for anons, right
