### ISSUE TITLE
[FTR] Enhance Direct Messages

### ISSUE THREAD

**Issue by saloniamatteo** [austinhuang0131/barinsta#32]
**Is your feature request related to a problem? Please describe.**
In DMs, we should be able to:

[GROUPS]
+ Help users tag group members:
    - For example, if there's a group with 3 people "foobar", "barbaz" and "bazbarfoo", user "foobar" should be able to start typing `@baz` and InstaGrabber should show the closest match to the username;
+ Show group members;
+ Show group options;

[MEDIA]
+ Like message/double tap message to like;
+ Send other media (like photos):
    - Currently we can only send text messages and posts.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
No alternatives possible AFAIK

**Additional context**
None.

**Comment by austinhuang0131** [comment]
yeah ofc that'll happen eventually but i'm still quite a beginner so like be patient

**Comment by GoDzM4TT3O** [comment]
No worries, take your time :)

**Comment by ammargitham** [comment]
Task list

- [ ] Send photos in direct messages (#52)
- [ ] Tag group members
- [ ] Like message

**Comment by landry314** [comment]
Also, I would like to click on a person's icon while reading their DM to open their main page. This is how instagram works in a web browser. It is a quick way to get to someone's page to find their posts when you had a message from them recently but you don't remember how to spell their instagram name.

**Comment by austinhuang0131** [comment]
it does do that now, if you mean profile pic next to message

**Comment by austinhuang0131** [comment]
group info task list

- [ ] edit title & settings
- [ ] member management

**Comment by landry314** [comment]
i actually meant while looking at the list of conversations. tapping on the profile pic next to the conversation could pull up their main page.
