### ISSUE TITLE
[BUG] Repeated DMs

### ISSUE THREAD

**Issue by RickyM7** [austinhuang0131/barinsta#320]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

If you write a message and click quickly and repeatedly the send button, the same message will be sent several times (I think this happens according to the connection speed).

## Steps

1. Go to 'DM'
2. Click on any profile that is there
3. Write a message and quickly and repeatedly click the send button

## Environment

 - Device: Redmi Note 4
 - Android version: 7.0

**Comment by ammargitham** [comment]
Will fix in DM update

**Comment by austinhuang0131** [comment]
is this still applicable

**Comment by ammargitham** [comment]
Can be closed. Since the new DM update fixes it.
