### ISSUE TITLE
[BUG] Light mode system navbar when post is open in black mode

### ISSUE THREAD

**Issue by emmatebibyte** [austinhuang0131/barinsta#326]
- [X] My app is on the latest version. I understand that any other version is not supported.
- [X] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

Open an image in the feed and the navbar is white when it should be black.

## Environment

 - Device: Samsung Galaxy A505U
 - Android version: 10

## Additional info
Image attached

**Comment by austinhuang0131** [comment]
Your image is not attached

Post viewer doesn't have light mode AFAIK so I'll put this as enhancement

**Comment by emmatebibyte** [comment]
![Screenshot_20201122-175008_Barinsta](https://user-images.githubusercontent.com/58507086/100659652-e93c2300-331e-11eb-912d-c2245f4f0217.jpg)
