### ISSUE TITLE
[FTR] use barinsta without account

### ISSUE THREAD

**Issue by 0xFEDERICO** [austinhuang0131/barinsta#327]
**Is your feature request related to a problem? Please describe.**
I use instagram mainly to follow public pages and as far as I'm concerned I don't need an instagram account.

**Describe the solution you'd like**
I think your app would become truly unique if you could see the stories and posts (barinsta already offers this feature) on the home page of only your favorite accounts.

**Additional context**
I believe that in this way we can give a big blow to this digital giant called facebook because people would not be obliged to have an account and necessarily provide personal data.

**Comment by austinhuang0131** [comment]
https://www.reddit.com/r/barinsta/comments/jz5yzm/is_there_any_plans_to_make_stories_and_highlights/
