### ISSUE TITLE
[FTR] Some UI Improvements

### ISSUE THREAD

**Issue by RickyM7** [austinhuang0131/barinsta#335]
**Is your feature request related to a problem? Please describe.**

It would be interesting if some small changes were made to the UI to make the navigation simpler, these changes would make the Barinsta UI a bit like the official Instagram app, but it would still have some differences.

**Describe the solution you'd like**

- [ ] 1. The "Activity" option should be added to the bottom bar.

- [ ] 2. Merge the search option seen in the "Profile" tab with the "Discover" option/tab.

- [ ] 3. The "DM" option should be in the top bar, next to the layout option and be accessable by dragging the screen from right to left or by clicking the DM icon as well as in the official app.

- [ ] 4. The topic "For You" should always be open in the "Discover" tab and the other topics should be just below the search bar.

**Additional context**

| Home/Feed Example | Discover Example |
| --- | --- |
| ![Home - UI Example](https://user-images.githubusercontent.com/24703825/100142106-1e092f80-2e72-11eb-86aa-0eebca4a43f5.png) | ![Discover - UI Example](https://user-images.githubusercontent.com/24703825/100142078-177ab800-2e72-11eb-99c1-2c53a2ed88f7.png) |
| - The "Activity" option should be added to the bottom bar  | - Merge the search option seen in the "Profile" tab with the "Discover" option/tab |
| - The "DM" option should be in the top bar, next to the layout option and be accessable by dragging the screen from right to left or by clicking the DM icon as well as in the official app | - The topic "For You" should always be open in the "Discover" tab and the other topics should be just below the search bar, as well as in screenshot |
| Note: If the option to add posts is added to the app, the "+" button (the create post button seen in the screenshot) should be somewhere in the profile tab, after all this is directly related to the profile. | Note: If the search option is merged with the "Discover" tab, I think it's worth removing this from the profile tab. |

**Comment by austinhuang0131** [comment]
Yes, I know how the actual Instagram app works, but there are some intentional "anti-addictive" design consideration in Barinsta that are _against_ your suggestions.

1. Hiding Activity will prevent constant check of notifications (addiction), so that you can focus less on "engagement" and kinda stuff.
2. We'll eventually merge Search with Favourites so that anonymous users can access them more conveniently, which makes your suggestion impossible (note that anons don't have Discover).
3. Having a more obvious DM button emphasizes on communication.
4. (Methinks, though I didn't design that part,) having topics listed separately (instead of immediately listing 1 topic) will also allow you to consider which topic you'll be reading _before_ being too addicted within "For you".

**Comment by RickyM7** [comment]
>Yes, I know how the actual Instagram app works, but there are some intentional "anti-addictive" design consideration in Barinsta that are against your suggestions.

>1. Hiding Activity will prevent constant check of notifications (addiction), so that you can focus less on "engagement" and kinda stuff.
2. We'll eventually merge Search with Favourites so that anonymous users can access them more conveniently, which makes your suggestion impossible (note that anons don't have Discover).
3. Having a more obvious DM button emphasizes on communication.
4. (Methinks, though I didn't design that part,) having topics listed separately (instead of immediately listing 1 topic) will also allow you to consider which topic you'll be reading before being too addicted within "For you".

Thanks for the answers. I would never have imagined that the position of certain options was purposeful to avoid certain addictions, I honestly think this is great. Thank you for your great work.
