### ISSUE TITLE
[BUG] There should be no open action for posts in the single column layout

### ISSUE THREAD

**Issue by 532910** [austinhuang0131/barinsta#359]
1. It's useless.
2. The playback must be started by the fist tap

![ScreenRecord-2020-11-30-07-02-03](https://user-images.githubusercontent.com/14617699/100568028-08b15c80-32db-11eb-84f3-a50e3f92b8f7.gif)

Version 19.0.1 from F-Droid, LineageOS 17.1 + microG, OP3t

**Comment by ammargitham** [comment]
Not a bug. This is intentional.

**Comment by 532910** [comment]
I see nothing intentional here. Please reopen. It's very inconvenient to take three steps to start playing a video.
