### ISSUE TITLE
[BUG] video playback controls should be hidden on start

### ISSUE THREAD

**Issue by 532910** [austinhuang0131/barinsta#360]
Video playback controls should be hidden on start, and shown only after the second tap.

![ScreenRecord-2020-11-30-07-02-03](https://user-images.githubusercontent.com/14617699/100568181-85443b00-32db-11eb-826e-c39fd57412b8.gif)

Version 19.0.1 from F-Droid, LineageOS 17.1 + microG, OP3t

**Comment by ammargitham** [comment]
@austinhuang0131 I think this has been fixed.

**Comment by 532910** [comment]
Current release from f-droid looks the same.
