### ISSUE TITLE
[BUG] scrolling speed is faster on the top of the profile

### ISSUE THREAD

**Issue by 532910** [austinhuang0131/barinsta#362]
Not sure if this was intended, but it's very annoying behavior.
![ScreenRecord-2020-11-30-07-20-35](https://user-images.githubusercontent.com/14617699/100568703-fa644000-32dc-11eb-8d56-8ab0035b2785.gif)

**Comment by austinhuang0131** [comment]
#273

**Comment by 532910** [comment]
So this issue should be closed?
