### ISSUE TITLE
[FTR] Put Favorites closer

### ISSUE THREAD

**Issue by 532910** [austinhuang0131/barinsta#363]
On the bottom panel, for example:
![image](https://user-images.githubusercontent.com/14617699/100568925-95f5b080-32dd-11eb-948c-3a7ab9342fd4.png)

**Comment by austinhuang0131** [comment]
I'm more favoured towards moving faves to search (ie. as results when empty search string) so yeah it would be incompatible

**Comment by 532910** [comment]
I'd prefer to see favs in `what's new` feed, like in NewPipe, for example.
