### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Stenafo** [austinhuang0131/barinsta#365]
If on the feed someone writes the username of a profile that contains points, the application will stop at the first point of the username, and clicking on it will take you to another profile.
Example: if I write @alex.exam.97 in the description of a photo
I will have the application select only @ alex as username. (**@alex**.exam.97)

**Comment by austinhuang0131** [comment]
Fixed by https://github.com/ammargitham/AutoLinkTextViewV2/commit/bb11a22f595f5774fd6122c72ba8bdacbcbdfcd0
