### ISSUE TITLE
[FTR] Live videos

### ISSUE THREAD

**Issue by forcemagic** [austinhuang0131/barinsta#383]
**Is your feature request related to a problem? Please describe.**
Yes, it is kind of related to one. In the instagram app (feed view) I can see the people who are currently broadcasting live, in the first (couple) reels. In this app, I can't. Also, I would like to view a stream without "actually being in there" (without showing up on the viewers list).

**Describe the solution you'd like**
[This](https://github.com/austinhuang0131/barinsta/blob/951117c769f4f4559ece5df533967b0e969df084/app/src/main/java/awais/instagrabber/asyncs/FeedStoriesFetcher.java#L33) is the suspected URL for getting the stories, it should be changed accordingly to show live feeds as well. Also, lives are returned in dash format, which is convenient, since [exoplayer-dash](https://exoplayer.dev/dash.html) is bound to support fMP4, which I believe is returned from instagram.

Thank you in advance! If you need any help, even though I am not very skilled in Java, I might just be able to give some pointers. Maybe open a PR later. 😄

**Comment by austinhuang0131** [comment]
Maybe give me an account that does livestreams? I feel like browser versions don't support livestream so setting it to true wouldn't do anything, but I also don't follow such accounts...

But yeah... if you think you can PR, then you should give it a try, after all this project is open source for a reason! And I am not very skilled in Java either (yes, my only experience is this project)

**Comment by austinhuang0131** [comment]
no response, will put help-wanted tags

**Comment by austinhuang0131** [comment]
Reels tray => "broadcast" array, then each object:

```json
    {
      "id": 123456789,
      "dash_playback_url": "a .mpd link on instagram cdn",
      "dash_abr_playback_url": "a .mpd link on instagram cdn, this one with adaptive quality",
      "broadcast_status": "active",
      "viewer_count": 2.0,
      "internal_only": false,
      "muted": false,
      "ranked_position": 0,
      "seen_ranked_position": 0,
      "cover_frame_url": ".jpg link",
      "cobroadcasters": [
      ],
      "is_player_live_trace_enabled": 0,
      "is_gaming_content": false,
      "is_live_comment_mention_enabled": true,
      "is_live_comment_replies_enabled": true,
      "is_viewer_comment_allowed": true,
      "broadcast_owner": {
        "pk": 174658321,
        "username": "sample_username",
        "full_name": "sample user",
        "is_private": true,
        "profile_pic_url": "avatar",
        "profile_pic_id": "12345_6789",
        "friendship_status": {
          "following": true,
          "followed_by": true,
          "blocking": false,
          "muting": false,
          "is_private": true,
          "incoming_request": false,
          "outgoing_request": false,
          "is_bestie": false,
          "is_restricted": false
        },
        "is_verified": false,
        "live_subscription_status": "default"
      },
      "published_time": 1609897109,
      "hide_from_feed_unit": true,
      "video_duration": 0.0,
      "media_id": "12345_6789",
      "live_post_id": 987654321,
      "broadcast_message": "",
      "organic_tracking_token": "oewajgrebjnwjgesknbdlkjnwef=",
      "dimensions": {
        "height": 2733,
        "width": 1440
      },
      "broadcast_experiments": {
        "ig_live_viewer_redesign_broadcaster_v1": {
          "aspect_ratio_change_enabled": false,
          "comment_redesign_combined_test_enabled": false,
          "viewer_redesign_combined_test_enabled": false
        },
        "ig_allow_4p_live_with": {
          "allow": false
        },
        "ig_cs_output_host_provided_resolution": {
        }
      },
      "visibility": 0
    }
```
