### ISSUE TITLE
[BUG] Usernames in comments sometimes not showing correctly

### ISSUE THREAD

**Issue by Raniconduh** [austinhuang0131/barinsta#408]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

Usernames in comments do not display correctly and clicking on them may take you to the profile of a different user.

E.g. if user `user.name` comments on a post and someone comments under their comment, the highlighted portion of `@user.name` will only be before the period. Tapping on `@user.name` will then take you to `@user`, completely ommiting the part after the period.

## Steps

1. Open the comments of any post anywhere
2. Look for a comment by someone with a period in their username
3. See the comments under the comment of the person with a period in their username
4. Click on `@user.name` (or whatever the username is) in the subcomments under the commenter with a period in their username
5. Watch as you are taken to a different user who's username is the same as the one you clicked on, but ommiting anything after the first period.

## Environment

 - Device: LG G7 ThinQ
 - Android version: 8.0.0

**Comment by austinhuang0131** [comment]
self reminder: convert [this](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/res/layout/item_comment.xml#L56) to autolink
