### ISSUE TITLE
[BUG] Discover thumbnail not loading

### ISSUE THREAD

**Issue by altunyurt** [austinhuang0131/barinsta#412]
- [ x] My app is on the latest version. I understand that any other version is not supported.
- [x ] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

Some content are not loaded and displayed as empty blocks. These blocks eventually display content in popup when tapped on, but this doesn't fix the block itself.
Please see the screenshot.

![Screenshot_20201212-212622.png](https://user-images.githubusercontent.com/126674/101992053-a46e9f80-3cc1-11eb-841b-93a539d6ad19.png)

## Steps
1- Just use the app normally.

## Environment

 - Device: Moto e4 plus
 - Android version: 7.1.1

**Comment by austinhuang0131** [comment]
Can't reproduce on Android 9

**Comment by altunyurt** [comment]
Sorry about the missing title, I couldn't get used to github mobile app yet. 

Apparently only multipage contents are displayed as empty blocks. Force refreshing the feed doesn't fix it and the newly fetched content also have empty blocks for the multipage items. 
As mentioned, they are displayed perfectly fine in popup layer when tapped on the block. 

I'll update if adb logcat gives any clues.

**Comment by austinhuang0131** [comment]
Okay, so someone else did give me context and I'll try to fix it. In the meantime, change your layout to square instead.
