### ISSUE TITLE
[FTR] Video playback is 2 step and has the strange dimming of the rest of the screen

### ISSUE THREAD

**Issue by needleworker0** [austinhuang0131/barinsta#416]
**Is your feature request related to a problem? Please describe.**

1. Please avoid this strange dimming of other parts of screen (or overlay or whatever) while playing video. And please avoid the description popup while at first click. A typical ig user does not want these. Please
2. Please just play video.

**Describe the solution you'd like**
Let it just play video. 

 if one wants read description let them click the description icon. 

The user pressed play button - so let it play video.  Should not be 2 steps.

**Additional context**

Thanks for the app.
![1](https://user-images.githubusercontent.com/66745085/102019861-143e6200-3d76-11eb-8bc2-7112f3b266af.png)

**Comment by austinhuang0131** [comment]
moved to #464 

It's not "strange dimming", it's just opening the post viewer dialog because we removed autoplay
