### ISSUE TITLE
[FTR] Follow without an account

### ISSUE THREAD

**Issue by anin1354** [austinhuang0131/barinsta#430]
**Is your feature request related to a problem? Please describe.**
Is it possible to follow accounts and save them locally without signing in? I hate Instagram with a passion, but there's a few public profiles I wish to follow. Facebook decided my burner account should be deleted and they wanted a picture of my face to reactivate it. So I'm turning to this app.

**Describe the solution you'd like**
Ability to follow public accounts without an account, as well as notifications when they post.

**Additional context**
Please flesh out the non account features as much as possible, I am hoping for this project to be the solution to my problems.

**Comment by austinhuang0131** [comment]
Duplicate of #24
