### ISSUE TITLE
[BUG] Increase the size of the layout menu

### ISSUE THREAD

**Issue by RickyM7** [austinhuang0131/barinsta#431]
### Is your feature request related to a problem? Please describe.
The layout menu is quite small, so I had to change some translations to prevent them from appearing cut (as in the screenshot in Additional context)

### Describe the solution you'd like
Simply increasing the size of the menu or decreasing the text size within it would solve this problem, I think.

### Additional context
![layout_float_menu](https://user-images.githubusercontent.com/24703825/102713815-7bde3b00-42a9-11eb-9193-63274a46f6f9.jpg)

**Comment by austinhuang0131** [comment]
screen sizes are annoying so might fix might not fix

**Comment by RickyM7** [comment]
That's not a very serious problem in my opinion, so I think it's okay if it's not fixed.
Btw, wouldn't it be possible to activate the wrap lines in this part to fix this bug?

**Comment by RickyM7** [comment]
@austinhuang0131 Looks like the bug has been fixed on v19.0.3. In case I find another problem in this I will comment but I am closing the issue now.
