### ISSUE TITLE
Material Dark Green Color Is Too Close To White

### ISSUE THREAD

**Issue by landry314** [austinhuang0131/barinsta#437]
When using the Material Dark theme the greenish color is so faded it is barely distinguishable from the white color. This makes it hard to see quickly where the toggles are.

**Comment by austinhuang0131** [comment]
what greenish? where?

**Comment by landry314** [comment]
![Screenshot_20201223-010407_Barinsta](https://user-images.githubusercontent.com/6866501/102947432-51e76d00-4491-11eb-98f9-6d26fdfe0c29.png)

**Comment by austinhuang0131** [comment]
![Screen Shot 2020-12-22 at 21 55 59](https://user-images.githubusercontent.com/16656689/102953983-86165a00-44a0-11eb-8036-d20168ed750a.png)

satisfied?

**Comment by landry314** [comment]
i'm using the "dark" theme, just trying to help.

**Comment by austinhuang0131** [comment]
That *is* material dark.

**Comment by landry314** [comment]
oops, i meant "black". thanks.
