### ISSUE TITLE
Backup & Restore Function Names Can Be Cleaner

### ISSUE THREAD

**Issue by landry314** [austinhuang0131/barinsta#438]
In the Backup & Restore section of Settings you currently have two options, "Create" and "Restore".

Considering the name for the section is "Backup & Restore", I suggest the two functions be renamed to:

Backup
Restore

OR

Change the name of the section to simply "Backup" and the two functions to:

Create Backup
Restore Backup

This is logically cleaner. Either the section is called "Backup" for the two kinds of backup procedures, "Create" and "Restore" (suggestion 2) OR it is called "Backup & Restore" for the two functions "Backup" and "Restore" as in its title (suggestion 1).

**Comment by austinhuang0131** [comment]
```
Settings Backup
→ Create backup
→ Restore backup
```

is that good?

**Comment by landry314** [comment]
"Backup app settings, account login information, and/or favorites data to a plain text or encrypted backup file for later restoration."

How's that?

**Comment by austinhuang0131** [comment]
![Screen Shot 2020-12-27 at 21 19 08](https://user-images.githubusercontent.com/16656689/103185186-3d3c1800-4889-11eb-8503-b975755ed4e9.png)

**Comment by landry314** [comment]
"create new backup file"

**Comment by landry314** [comment]
Two small things with new release...

1) "Backup and Restore User Settings" doesnt contain any settings, just two functions, backup and restore... I would drop the words 'user settings'.

2) "keep them somewhere safe" should be "keep it somewhere safe" because it = "the file". It is singular. "them" is plural.

**Comment by austinhuang0131** [comment]
1. "Backup and Restore" as verb, "User Settings" as subject
2. oh ok

**Comment by landry314** [comment]
The words "User Settings" are not correct there. There are no user settings in that section, just the functions of backup and restore. I would rename it to just "Backup and Restore"

**Comment by landry314** [comment]
also the grammar is still wrong with 'the file' = 'them'. 'the file' = it. "keep it somewhere safe".

**Comment by austinhuang0131** [comment]
@landry314 You can PR it?

**Comment by landry314** [comment]
i can learn how to do it. sure. i will learn.

**Comment by austinhuang0131** [comment]
You can just edit `/app/src/main/res/values/strings.xml`
