### ISSUE TITLE
[BUG] v19.0.3 Bugs

### ISSUE THREAD

**Issue by RickyM7** [austinhuang0131/barinsta#441]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

1. The "Tagged" option is cut if the translation of it or "Add to favorites" is large.

2. It is not possible to see the following users and because of this it is also not possible to compare followers.

## Steps
I don't think it's necessary.

## Environment

 - Device: Redmi Note 4
 - Android version: MIUI 11 (Android 7.0)
- App version: v19.0.3 (GitHub)

## Additional info
| Bug with "Tagged" in pt-BR |
| --- |
| ![Tagged](https://user-images.githubusercontent.com/24703825/103005410-b1d12880-4510-11eb-890e-0df5000b68c4.jpg) |

**Comment by austinhuang0131** [comment]
1. yeah it depends on translation (and screen size)
2. but you can see it? (also clicking either follower or following then eye button will give you the same comparison)

**Comment by RickyM7** [comment]
> 1. yeah it depends on translation (and screen size)

But you will try to fix this in some way or it is better that translators of the languages affected with this problem make changes to the translation so that the problem is fixed?

> 2. but you can see it? (also clicking either follower or following then eye button will give you the same comparison)

I can't see followers in any way and also can't compare followers regardless of whether I try by followers or followers.

**Comment by austinhuang0131** [comment]
1. I'll shorten the source string so that everyone can re-translate it
2. But the screenshot has it?

**Comment by RickyM7** [comment]
> 1. I'll shorten the source string so that everyone can re-translate it

Thank you.

> 2. But the screenshot has it?

I didn't quite understand. If it's about the screenshot of the issue, then it doesn't show anything about it and if you're wanting me to take a screenshot then here's.
![following](https://user-images.githubusercontent.com/24703825/103012933-142f2680-451b-11eb-93a3-b2094a91bd52.jpg)
![compare](https://user-images.githubusercontent.com/24703825/103012939-172a1700-451b-11eb-8544-db783ea99472.jpg)
