### ISSUE TITLE
[BUG] Message button missing in RTL layout

### ISSUE THREAD

**Issue by barudaret** [austinhuang0131/barinsta#443]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

Basically, a button is missing in RTL.  I have it in farsi, and not only is the message button missing, but sometimes the other buttons glitch out and show up in weird places.

## Steps

1. Put barinsta in farsi or arabic
2. Navigate to someone else's profile
3. See missing "Message" button
4. _Maybe_ see "Tagged" button in strange place too

## Environment

 - Device: Samsung GS20
 - Android version: 11

## Additional info

Here's some screenshots
![Screenshot_20201223-191554_Barinsta](https://user-images.githubusercontent.com/32847759/103055537-bb31b380-4557-11eb-8f42-5319b81181eb.jpg)
![Screenshot_20201223-191627_Barinsta](https://user-images.githubusercontent.com/32847759/103055538-bbca4a00-4557-11eb-9ea4-e7761cf6cd9d.jpg)

**Comment by austinhuang0131** [comment]
Try updating it (which changes the layout)

Reopen if persists

**Comment by barudaret** [comment]
Got the update, and even though it has a new layout, the message button still disappears in farsi.

English:
![Screenshot_20201227-174221_Barinsta_1_1](https://user-images.githubusercontent.com/32847759/103182822-8bdab980-486b-11eb-98f7-401687f6ec70.jpg)


Farsi:
![Screenshot_20201227-174205_Barinsta_1_1](https://user-images.githubusercontent.com/32847759/103182800-6057cf00-486b-11eb-8dc9-04619b3265d6.jpg)

**Comment by barudaret** [comment]
Some reason, github is not offering me the option to reopen this.

**Comment by austinhuang0131** [comment]
on a side note you should translate this app to Persian (see pinned issue for instructions)
