### ISSUE TITLE
[BUG] DM list is empty...

### ISSUE THREAD

**Issue by barudaret** [austinhuang0131/barinsta#444]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

... but if I click "Messages" button on an acc that I've DM'd, then the conversation shows up.

## Steps

1. Go to DM tab 
2. Empti
3. ¯\\\_(ツ)\_/¯ 

## Environment

 - Device: Samsung GS20
 - Android version: 11

## Additional info

![Screenshot_20201223-194913_Barinsta](https://user-images.githubusercontent.com/32847759/103055777-65a9d680-4558-11eb-81c2-09116cc36514.jpg)

**Comment by austinhuang0131** [comment]
When was the last time that the DM list worked properly?

From that point to now, what threads have new messages? What kind of messages?

**Comment by Aaddilll** [comment]
Yes bro?

**Comment by Aaddilll** [comment]
> When was the last time that the DM list worked properly?
> 
> From that point to now, what threads have new messages? What kind of messages?

Yes bro

**Comment by Aaddilll** [comment]
My dm list is not showing? What to do

**Comment by barudaret** [comment]
> When was the last time that the DM list worked properly?

Oh I wouldn't know, sorry.  I only discovered your project recently.  I'll wait for fdroid to update and i'll let you knew what happens then

**Comment by austinhuang0131** [comment]
> Oh I wouldn't know, sorry. I only discovered your project recently. I'll wait for fdroid to update and i'll let you knew what happens then

This part wasn't changed in the update, so it's irrelevant.

Usually it's because there's a bad message... Unfortunately I can't just ask for your account so it's a bit difficult to resolve this kind of stuff. You could try sending a text message in each thread where its last message is not text, then see which thread is causing problems, 1 by 1.

**Comment by caviidae** [comment]
this just happened to me. my dm list was fine until somebody I had not messaged yet had tagged me in their story. I fixed it by logging in to instagram web and messaging that person and now my dm list shows up fine

**Comment by ammargitham** [comment]
This has been fixed in the upcoming update of the dm module
