### ISSUE TITLE
[BUG] Can't send direct message if the text contains quotes

### ISSUE THREAD

**Issue by rafael-ferro** [austinhuang0131/barinsta#453]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

The error message (_Unknown error occurred!!!_) appears when trying to send text that contains quotes.

## Steps
1. Go to direct messages and choose a chat
2. Type some text and include some word in quotes (this character ")
3. When trying to send the message, the an error is shown and the app won't send the message

## Environment

 - Device: Mi 9 Lite
 - Android version: 10

## Additional info
![barinsta](https://user-images.githubusercontent.com/44897482/103160876-b7e93280-47b8-11eb-80b3-de7bb47013aa.jpeg)

**Comment by austinhuang0131** [comment]
For now, typing `\"` will be converted to `"`
