### ISSUE TITLE
 [BUG] A display issue

### ISSUE THREAD

**Issue by franklinbill** [austinhuang0131/barinsta#455]
- [√] My app is on the latest version. I understand that any other version is not supported.
- [√] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, The button in the red box cannot be displayed. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display. I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165928-96d81e80-4858-11eb-98a7-bad87176808d.png)

App version is 19.0.2, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
<img width="475" alt="bug-instagrabber" src="https://user-images.githubusercontent.com/18572115/103165925-917ad400-4858-11eb-8795-5fe96a3648ff.png">

## Steps

1. Go to first
2. See error

## Environment

 - Device: Google nexus 6
 - Android version: Android 8.0

**Comment by austinhuang0131** [comment]
I may or may not have addressed it in #431.

Assuming you're using F-Droid, wait for v19.0.3

**Comment by austinhuang0131** [comment]
![Screen Shot 2020-12-27 at 21 30 30](https://user-images.githubusercontent.com/16656689/103185527-d0298200-488a-11eb-99ea-98d5ff16cc99.png)

**Comment by austinhuang0131** [comment]
I'm not receiving any responses, therefore considering it fixed.

I do not believe opening 100 issues across several repositories in a short period of time is in good faith, even if when you're raising a valid point.

**Comment by franklinbill** [comment]
Thanks*100000 for your reply! After running 19.0.3, the problem of text has been fixed and can be displayed normally.
![barinsta](https://user-images.githubusercontent.com/18572115/103342227-f1c17e00-4ac3-11eb-8705-31c4407889c3.png)
