### ISSUE TITLE
Add "unlike" button in Liked section.

### ISSUE THREAD

**Issue by 27421** [austinhuang0131/barinsta#456]
Hey there,
I'm very impressed with the App and the overall smoothness of the whole UI. Its one of the best alternative clients i can think of.

I only miss one feature:
I want to be able to unlike selected Posts in the "liked" section at once, just like I can download them as a bunch. This would make it way faster and easier to get some things out of there if i already saw enough of in the preview.

I'm not so good at coding apps so I hope someone can include it in the Future, if this can be implemented somehow.

**Comment by austinhuang0131** [comment]
Mass (un)liking (or any other interaction) will probably be interpreted as botting which means you'll lose your account

Download is different because we don't fetch posts again
