### ISSUE TITLE
[Q] Issues Clean-up

### ISSUE THREAD

**Issue by AnonymousSeal** [austinhuang0131/barinsta#457]
I wanted to suggest some UI and general behaviour improvements while also avoiding to create duplicates and I found it really hard, because issues often feature more than 5 different topics.

For the sake of **avoiding duplicates**, and **cleaner issues** I would suggest

1. to tell people to **seperate** requests which handle **different topics** and also

2. to **combine all issues about UI** changes which have been posted before now to one issue for a **big release**

as both of these changes would make it easier to contribute ideas to this really cool project :)

**Comment by austinhuang0131** [comment]
1. Many people write emails into the issue section, so while it is easy to enforce so on GitHub, it is quite difficult for emails.
2. #243 is converted to a discussion. I'll also aggregate other UI suggestions.

**Comment by austinhuang0131** [comment]
#458
