### ISSUE TITLE
[Q] What does this red dot mean

### ISSUE THREAD

**Issue by AymenStudios** [austinhuang0131/barinsta#463]
I noticed a red dot over my friend's avatar in Direct Messages
What does this point mean
![Screenshot_20201228-201029](https://user-images.githubusercontent.com/45848768/103237805-0e857680-4949-11eb-93c3-25bdafcd1b74.png)

**Comment by RickyM7** [comment]
This indicates a new direct message.

@austinhuang0131 About this, could you add this new message indicator directly to the DM icon? This would make it much easier to know that there is a new message.

**Comment by AymenStudios** [comment]
There are then two problems
The first problem is the color that does not imply that there is a message
Secondly, this point is stuck even though there is no unread message
I read all the messages, but the point did not disappear from this account as it is in the picture
I think the red dot should be replaced by the green one for the active state

**Comment by RickyM7** [comment]
@AymenStudios I also have problems with this point not disappearing, but it seems that later will have an update focused on DMs, so I preferred to wait.

**Comment by austinhuang0131** [comment]
> The first problem is the color that does not imply that there is a message

iOS uses red dots

> Secondly, this point is stuck even though there is no unread message

Did you mark them as read (either through eye button, or automatic mark-as-read setting)? For privacy reasons we allow you to withhold read state from Instagram.

**Comment by AymenStudios** [comment]
Yes, I marked as read

**Comment by Shadowspear123** [comment]
Yea, I also have a chat where the red dot seems to be "stuck".

**Comment by austinhuang0131** [comment]
Removed and revamped in #503 but the new indicator seems to persist to have location issues
