### ISSUE TITLE
[BUG] on first logon after installation, DMs are shown above "More" screen

### ISSUE THREAD

**Issue by GenosseFlosse** [austinhuang0131/barinsta#472]
- [ :+1: ] My app is on the latest version. I understand that any other version is not supported.
- [ :+1: ] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

![signal-2020-12-29-093541](https://user-images.githubusercontent.com/59205524/103271512-bedf9300-49ba-11eb-8789-3ba4368bf2f1.jpeg)
DMs are shown above "more" screen. This only appears on first login. After killing and restarting the app, the DMs are shown just fine.

## Steps
I can reproduce the error as follows:
1. Clean install from fdroid and login to my instagram.
2. Go to DMs
3. Click on any DM contact

## Environment

 - Device: Pocophone f1
 - Android version: 10, MIUI 12.0.2

## Additional info

I don't have any log. Is there some option to enable logging?

**Comment by ammargitham** [comment]
Fixed in #955
