### ISSUE TITLE
[FTR] Allow users to choose folder from removable storage for custom folder option

### ISSUE THREAD

**Issue by ammargitham** [austinhuang0131/barinsta#48]
**Is your feature request related to a problem? Please describe.**
Users should have the ability to select a folder from the removable storage for saving to custom folder option in settings.

**Describe the solution you'd like**
Option to navigate to removable storage dir.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
N/A

**Comment by HristianIliev** [comment]
Can you assign me to this issue?

**Comment by ammargitham** [comment]
Hi @HristianIliev. Thanks for helping us out. This feature has been discussed and was attempted implemented, but due to upcoming changes in Android 11, has been put on hold.

**Comment by ammargitham** [comment]
With #934, user will be able to select any folder their phone allows to. If their micro sd card is available to choose then all downloads will go there.
