### ISSUE TITLE
[BUG] cannot open DMs containing gifs

### ISSUE THREAD

**Issue by neekless** [austinhuang0131/barinsta#480]
- [x ] My app is on the latest version. I understand that any other version is not supported.
- [x ] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

DMs that have gifs in them cannot be opened by Barinsta. 

## Steps

1. Open a DM containing gifs (sent on official app). 
2. Observe error. 

## Environment

 - Device: pixel 2 xl
 - Android version: 11

## Additional info

![Screenshot_20201230-142924](https://user-images.githubusercontent.com/22426822/103334513-93d56c00-4aac-11eb-8ef5-f87487d1f60f.png)

![Screenshot_20201230-142936](https://user-images.githubusercontent.com/22426822/103334421-2d504e00-4aac-11eb-8961-e4e159ac1470.png)

![Screenshot_20201230-144217](https://user-images.githubusercontent.com/22426822/103334720-6dfc9700-4aad-11eb-986e-53f88a0522a7.png)

**Comment by austinhuang0131** [comment]
how do you send gif?

**Comment by neekless** [comment]
You can send gifs in the official app

![Screenshot_20201231-030632](https://user-images.githubusercontent.com/22426822/103375691-cb2c3300-4b15-11eb-90cf-042a9daf2417.png)

![Screenshot_20201231-030644](https://user-images.githubusercontent.com/22426822/103375709-d2ebd780-4b15-11eb-86e2-1c085d479b39.png)
