### ISSUE TITLE
Viewing a photo is annoying, it keeps closing

### ISSUE THREAD

**Issue by steelbytes** [austinhuang0131/barinsta#481]
Viewing a photo is very very very very very annoying, it keeps closing when I zoom and pan as though it thinks I tried to swipe close the photo.  the only workable solution is to use the download button (thanks for this) and then view in a photo gallery app.

Android 11 / Pixel 3XL

**Comment by austinhuang0131** [comment]
temporarily removed in https://github.com/austinhuang0131/barinsta/commit/2b2f390f59040cca6446bcfbaa70644e1e1a40a3

**Comment by Shadowspear123** [comment]
This has to do with the sensitivity of the swipe to dismiss the image. Previously it used to require a much longer swipe which was then modified to a short swipe at the request of users. Looks like it needs to be fine tuned and balanced. How about making the the sensitivity a little less @austinhuang0131 @ammargitham thoughts?
