### ISSUE TITLE
[BUG] Stories and archive 

### ISSUE THREAD

**Issue by Amuro01** [austinhuang0131/barinsta#491]
- My app is on the latest version. I understand that any other version is not supported.
-  I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

• Stories are black if opened from profile page

• Stories are not marker ad seen as soon as I see them (yes, the privacy option in settings i setted so that the author knows when I see it) but it takes some time to have storiemarked as seen (they appear as new even if I have already seen them)

• Stories in the archive are shown with an incorrect time 
![Screenshot_20210101-013617_Barinsta](https://user-images.githubusercontent.com/39492812/103431537-c0cf6f00-4bd1-11eb-92e9-b06f57a05799.png)
Here we can see when the story was posted (incorrect time, equal for every story or almost equal)

![Screenshot_20210101-013625_Barinsta](https://user-images.githubusercontent.com/39492812/103431546-e2305b00-4bd1-11eb-87a9-2c4a9e533733.png)
Here we can see the real upload time of the story

This is a minor bug that doesn't affect in any significant way the user experience

## Steps

DETAILED Steps to reproduce the behaviour.
First bug (black stories):
1. Go to any user profile who posted a story in the last 24 hours
2. Click on profile picture to see stories
3. See error (black story)

Second bug (stories not marked as seen):
1. Enable "Marks stories as seen after viewing" in "Settings"
1.1 Normally when you see a story in your feed, Instagram marks the story as seen and moves the story to the end of the list
2. Stories already seen are marked as seen but are still in the first places of the list or they are not marked as seen at all

Third bug: 
0. See screenshots I shared 
1. Go to "More"
2.  Go to "Story archive"
3. See error

## Environment

 - Device: Oneplus 6 enchilada - LineageOS for microg
 - Android version: 10

**Comment by austinhuang0131** [comment]
1. fixing
2. It doesn't, it'll only mark as seen if you have read *all* stories of someone (intended). *Also,* there's some sort of issue about this (it'll only show read after refresh), I haven't figured out how to resolve that yet, so I'm putting it aside
3. apparently those timestamps are all "00:01:40 UTC on the expiry date" so I'll use a different timestamp instead
