### ISSUE TITLE
[BUG] Crashed on posts with comments disabled

### ISSUE THREAD

**Issue by R3zu4C** [austinhuang0131/barinsta#498]
- [✓] My app is on the latest version. I understand that any other version is not supported.
- [✓] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

Crashes when opening the comment section of a post with comments disabled.

## Steps

DETAILED Steps to reproduce the behaviour.
1. Go to any post with comments disabled.
2. Click on the post. 
3. Click on the comment button to open the comment section.

## Environment

 - Device: OnePlus Nord
 - Android version: 10

## Additional info

New Trace collected:
=====================

Error report collected on: Fri Jan 01 19:12:40 GMT+05:30 2021

Information:
==============
VERSION		: 19.0.3
VERSION_CODE	: 55
PHONE-MODEL	: AC2001
ANDROID_VERS	: 10
ANDROID_REL	: 29
BRAND			: OnePlus
MANUFACTURER	: OnePlus
BOARD

**Comment by austinhuang0131** [comment]
probably fixed ib #459 but give me a post link so I can make sure

**Comment by austinhuang0131** [comment]
I got your email, it doesn't crash in v19.0.4 anymore, but yeah I definitely should handle comment disabled
