### ISSUE TITLE
[BUG] 4 more bugs

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#532]
1. The links triggered from See More (Swipe Up) are opened in browser as https://instagram.com.

2. Individual story page: if I tap Mentions button and pick an account from that popup -> I visit that account -> I go back to that initial story page but it's displayed StoryViewFragment as header and the buttons on top disappear.

3. I browse the stories using the buttons on the bottom of the screen (left and right of thumbnails). Sometimes the next button simply disappears, like it's the end of the stories list despite more stories being unwatched yet.

4. After watching a story and going back to the main feed, pull to refresh doesn't work anymore.

**Comment by austinhuang0131** [comment]
1. I need a profile for me to test that
2.
3. 
4. Cannot reproduce (although if you click stories before the feed has loaded, it does become un-refreshable because the feed is empty)

**Comment by Kreuger** [comment]
Im having the same issue as #1.

**Comment by austinhuang0131** [comment]
@Kreuger As indicated, I need a profile link for me to test the story. (You can email me at im@austinhuang.me if you don't want to publicize)

**Comment by Kreuger** [comment]
It happens with any given link, not from one person. Does that matter?

**Comment by austinhuang0131** [comment]
The app does not alter the link, but your browser or another app could. As I said, I'll extract the `u` query parameter (which will also reduce Instagram tracking).
