### ISSUE TITLE
[BUG] Can't view stories sent to me via DM

### ISSUE THREAD

**Issue by caviidae** [austinhuang0131/barinsta#536]
- [x] My app is on the latest version. I understand that any other version is not supported.

- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

When people send/forward me stories via DM they show up in the DM list as "Unsupported message" and when I go into the DM I can see a thumbnail of the story with an action to "Show stories" but nothing happens when I click it.

Seems like the app assumes the story belongs to the person who sent it to me so it doesn't work. Since we can view stories by going to a persons profile I think we should be able to view stories sent to us. If not view them directly in the DM window, then maybe fix the link so that we can go to the profile of the actual story creator and view the story there.

## Steps

DETAILED Steps to reproduce the behaviour.
1. Go to DM of somebody who has sent you a story
2. Click on the story thumbnail
3. You are presented with 3 actions: Show stories, Like message, View author profile
4. Click 'Show stories' and nothing happens
5. Click 'View author profile' and you are taken to the profile of the person who sent you the message, not the person who the story belongs to, so there is no way to actually view the story or know who created it

## Environment

 - Device: OnePlus 7 Pro
 - Android version: 10

## Additional info

**Comment by austinhuang0131** [comment]
i think it's fixed in the pr but @ammargitham needs to confirm it

**Comment by austinhuang0131** [comment]
see v19.1.0-a1
