### ISSUE TITLE
[FTR] Share posts, profiles and/or stories via DM

### ISSUE THREAD

**Issue by caviidae** [austinhuang0131/barinsta#537]
In the regular app and website you have the option when viewing a post or story to share it to someone else on Instagram via DM easily.

Currently in Barinsta there is no way to send someone a story. For posts we have the share button which lets us copy the link and then paste that to someone, but it requires extra steps and after pasting the link all they see is a link, not the regular thumbnail you get when sharing on Instagram, which is a better user experience.

Would be cool if there was a share/forward button which let us select a user to DM the post/story to so that they can view it in place in the DM instead of just seeing a link.

**Comment by xbvrhlmb** [comment]
@austinhuang0131  Very necessary function! It would be nice if implemented

**Comment by xbvrhlmb** [comment]
@ammargitham have any luck?" we're really looking forward to it)

**Comment by ammargitham** [comment]
Sharing posts will be done soon. Stories will be done later.

**Comment by ammargitham** [comment]
- [x] Share posts
- [ ] Share profiles
- [ ] Share stories

**Comment by ammargitham** [comment]
> Cool to see it's now possible (tested on latest nightly). But looks like the final "send" button, when selecting the users, is just a white/black (depends on the theme) rectangle without text?

Just a theming issue. You can create a separate ticket for that.

**Comment by austinhuang0131** [comment]
<details>
<summary>Dev note only:</summary>

Currently the app will create all threads before sending the message. However, on the actual client, it is possible to have `recipient_users: [[1234567], [12345678]]` as sending to users who the client does not know the thread ID (locally) of. There is also `thread_ids: [1234567890, 12345678901]`

It is unclear whether `recipient_users` and `thread_ids` can be used together.
</details>
