### ISSUE TITLE
[FTR] search in someone's posts and stories

### ISSUE THREAD

**Issue by moshpirit** [austinhuang0131/barinsta#554]
When we open someone's profile we have a search button, but it's a regular searcher, it would be cool to have an option to search some text on this username's featured stories and posts

**Comment by austinhuang0131** [comment]
Posts are paginated, so the app will have to fetch all pages before searching, which Instagram will interpret as scrapeing, which could lead to an account/IP ban, so no

**Comment by moshpirit** [comment]
What about the featured stories?

**Comment by austinhuang0131** [comment]
I may entertain viewing highlights (proper term) as a list and may also entertain filtering stories (by username for feed, or by title for highlights) but I personally don't think a profile will post like more than 20 highlights
