### ISSUE TITLE
[BUG] Barinsta reports zero comments on discover topics images

### ISSUE THREAD

**Issue by rgabbo** [austinhuang0131/barinsta#573]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

When browsing images in any of "discover" topics, if I look at the bottom panel I find "0 comments" (see pic) but if I open comments panel they are often present in the same post.

## Steps

1. Start the app
2. Login
3. Go to Discover section
4. Open one topic
5. Open any image
6. See indicator reporting zero comments to the post

## Environment

 - Device: CAT S52
 - Android version: 9

![Screenshot_20210108-184910](https://user-images.githubusercontent.com/58396985/104048288-48753900-51e3-11eb-926d-323d6c0a3a30.png)

**Comment by ammargitham** [comment]
The api response returns 0 for comment count in discover. So not a bug.
