### ISSUE TITLE
Save Pictures as: Profilename-Date

### ISSUE THREAD

**Issue by benmeier95** [austinhuang0131/barinsta#577]
Hello everyone,
Pictures and videos are stored in a profile folder. However, the file name is cryptic. It would be good if the file names included the profile name and the date of the saves. Just like it is the case with the profile pictures. 

Current:
Photo 1: cjdpsf.jpg

Suggestion:
Photo 1: GoPro-2021-01-09-0001.jpg
Photo 2: GoPro-2021-01-09-0002.jpg

Thanks in advance and keep up the good work.

**Comment by austinhuang0131** [comment]
The filename is the shortcode (instagram.com/p/shortcode) because people asked so.
