### ISSUE TITLE
[FTR]Ability to view subscribers and subscriptions of an account

### ISSUE THREAD

**Issue by Artus777** [austinhuang0131/barinsta#585]
Ability to view subscribers and subscriptions of an account like nitter for anonymous use.

 Thank you

Sorry for my bad english

**Comment by austinhuang0131** [comment]
If you mean "following and followers", Nitter doesn't allow you to view them either...

Try writing in your native language and I'll get one of our translators

**Comment by Artus777** [comment]
Goch, you are right, this function is not on nitter. 

And yes, I meant "following and followers". 

Is it possible too have access to "following and followers" of  a given account in some way? 

Thank you in advance

**Comment by austinhuang0131** [comment]
No, you do have to log in, and I can't just use a central bot account to do it (ratelimiting + scrapeing ban).
