### ISSUE TITLE
[BUG] filename..jpg (two dots in downloaded file) FOR POSTS

### ISSUE THREAD

**Issue by mawed** [austinhuang0131/barinsta#595]
- [ X] My app is on the latest version. I understand that any other version is not supported.
- [ x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

When downloading an image, two dots before the filetype will be used within the filename.

## Steps

1. Download image via app
2. Check filename via file explorer
3. Find two dots before file type ( filename..jpg)
4. Different apps do not find the image as image

## Environment

 - Android version:10

**Comment by austinhuang0131** [comment]
What are you trying to download? Post? Story? Avatar?

**Comment by mawed** [comment]
I downloaded a post from profile.

For example:
![CI05xCzpzCc](https://user-images.githubusercontent.com/11197868/104486459-16414e00-55cc-11eb-9b4b-ec3b513af63c.jpg)

From https://instagram.com/p/CI05xCzpzCc
