### ISSUE TITLE
[BUG] As anonymous user, opening first profile works, rate limit kicks in with immediate next profile

### ISSUE THREAD

**Issue by sknorr-prv** [austinhuang0131/barinsta#606]
- [x] My app is on the latest version. I understand that any other version is not supported. -> 19.0.5
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

I am using Barinsta to browse public Instagram profiles without the horrid web interface getting in the way. About a week ago, Barinsta stopped working properly: When I open the app for the first time on any given day, the first profile does open. I can also view as many posts on that profile as I like. However, the immediate next profile that I go to will not load and Barinsta will show "Error loading profile!" in a toast.

Trying to open the same profile with a browser, the login form appears immediately (i.e. after allowing cookies), so apparently I run into rate-limiting. Location is Germany, I am not using VPNs or similar.

I wonder if the issue is that Barinsta ignores a GDPR prompt when opening the first profile and thus gets flagged immediately  -- though I guess that would only apply if Barinsta were scraping the website, not sure it works.

Turns out apparently they specifically block my Wi-Fi this way. I can turn off Wi-Fi and then, on LTE, immediately open multiple profiles in quick succession.

## Environment

 - Device: Sony Xperia XZ1
 - Android version: 9

**Comment by austinhuang0131** [comment]
Ever since Barinsta becomes a thing, they're like extremely wary of residential IPs rn

Good that I'm causing fear

**Comment by sknorr-prv** [comment]
Ugh :( No chance for a fix on Barinsta's end then?

**Comment by austinhuang0131** [comment]
We are trying... But the chance is quite small.

**Comment by sknorr-prv** [comment]
On desktop Chromium in private mode, this is what clicking the "Accept cookies" button causes (I used Chrome's copy-as-curl functionality):

```
curl 'https://www.instagram.com/web/__mid/' \
  -H 'authority: www.instagram.com' \
  -H 'accept: */*' \
  -H 'x-ig-www-claim: 0' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'x-web-device-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' \
  -H 'user-agent: ...' \
  -H 'x-ig-app-id: xxxxxxxxxxxxxxx' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.instagram.com/lowcostcosplayth/' \
  -H 'accept-language: en' \
  -H 'cookie: ig_cb=2' \
  --compressed
```

I replaced two items with "x"s, "web-device-id" is a hex string, "x-iq-app-id" is a decimal string.
