### ISSUE TITLE
[FTR] Search bio function

### ISSUE THREAD

**Issue by modelfe** [austinhuang0131/barinsta#614]
I was just wondering if it would be possible to implement a feature that would allow us to search instagram bios and websites of accounts we're following. E.g., if I searched for the word "dog", every profile bio containing the word dog would be listed. Or if I searched for "linktr.ee" all accounts I'm following with linktree links would appear.

I don't have the skill to do this myself, and have no idea how easy it would be to implement it, if it's possible at all. Just an idea.

Thank you for maintaining this app!

**Comment by austinhuang0131** [comment]
Instagram does not offer such search function so it'll require fetching profiles one by one which is a quick way to get banned
