### ISSUE TITLE
[FTR] username-filename.jpg In addition to username/filename.jpg save format

### ISSUE THREAD

**Issue by Sudrien** [austinhuang0131/barinsta#631]
Settings currently (19.0.5) has a "Download posts to username folders" option.

An additional "Prepend username to filename" - to preserve more info about the source of a file if it is shared or archived by a system without subfolder support.

Additional save & subfolder options as suggest by Instaprefs' configuration  settings include filesize, post timestamp, and file extension. That would probably  require  significantly more work.

**Comment by anoopspeaks** [comment]
Will be nice if filename will be like [username]-yyyymmdd-[####].ext
