### ISSUE TITLE
[FTR] Refresh button on DM

### ISSUE THREAD

**Issue by sigaloid** [austinhuang0131/barinsta#633]
**Is your feature request related to a problem? Please describe.**
DM's should have a refresh button on the top right so I don't have to go back and refresh when I'm waiting for a message
**Describe the solution you'd like**
Simple button on the top right next to the mark as seen button that refreshes that DM

**Comment by austinhuang0131** [comment]
there is also one in #503

**Comment by sigaloid** [comment]
wow I can't check PR's today. thanks

**Comment by austinhuang0131** [comment]
nah it wasn't too obvious but it's there
