### ISSUE TITLE
[FTR] Collapsed comments

### ISSUE THREAD

**Issue by creativetrendsapps** [austinhuang0131/barinsta#636]
Is there a way to have comments collapsed? Currently viewing comments have them all expanded which makes scrolling through them a long process. Maybe at a toggle to view more?

**Comment by austinhuang0131** [comment]
edited for format

**Comment by creativetrendsapps** [comment]
Yeah. Sorry using the GitHub app and didn't understand the formatting. Thanks for reopening.

**Comment by austinhuang0131** [comment]
this is implemented in v19.2.2
