### ISSUE TITLE
[FTR] DM requests

### ISSUE THREAD

**Issue by amuro0079** [austinhuang0131/barinsta#644]
Private accounts have a section for chats with strangers (who DM you first) separated from normal chats, so that the user fan accept or refuse to chat with the person who sente a message. 
The officiale client has a small icon in the top right corner of DM section that if pressed shows all requests from not followers/not followed, so that you can accept them or noto (just like a follow requests)

Barinsta does not have this feature yet.

**Comment by austinhuang0131** [comment]
currently included #503

**Comment by Amuro01** [comment]
> currently included in #503

Wow you were so fast that I couldn't even edit the spelling errors ahahah thanks
