### ISSUE TITLE
[BUG]Unfollowing private accounts does not work

### ISSUE THREAD

**Issue by vhateg** [austinhuang0131/barinsta#645]
- [X] My app is on the latest version. I understand that any other version is not supported.
- [X] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Unfollowing private accounts does not work. It simply refreshes the selected profile. After checking with the official app, it's not just a visual bug. The users are simply not unfollowed.

## Steps

1. Go to "Profile" tab
2. Touch "Following" or "Followers"
3. Touch the eye icon
4. Select any profile
5. Click "Unfollow"
6. If the profile is not private, it works. If it is private, though, the confirmation screen appears, and if "Confirm" is selected, the opened profile will be refreshed but the following status won't change.

This is how it happened the first time for me, but it also happens if the profile is simply searched.

## Environment

 - Device: Samsung Galaxy S7 Edge (SM-G935F)
 - Android version: 8.0.0

**Comment by austinhuang0131** [comment]
[It does work.](https://github.com/austinhuang0131/barinsta/blob/master/app/src/main/java/awais/instagrabber/fragments/main/ProfileFragment.java#L911) I cannot reproduce your issue. Are you actually on latest (v19.0.5)?

**Comment by vhateg** [comment]
I am on latest and it doesn't even work for public accounts now. I will do a reinstall later to confirm the problem.

**Comment by austinhuang0131** [comment]
no response
