### ISSUE TITLE
[FTR]Super-unfollow

### ISSUE THREAD

**Issue by vhateg** [austinhuang0131/barinsta#647]
This may not be the an extremely useful feature, but I think it can be easly implemented. I am but a novice programmer, so I may be wrong, though.

The said feature would be accessible through a button hidden in the three dots contextual menu on profile pages. It works just like a normal unfollow button, but automates the removal of all comments and likes that the user may have left on the pages that they wish to "super-unfollow" (or some other simmilar name)

Additional features such as: removing tags of said profile from users's own photos, deleting profile's comments on user's own page and other simmilar things may be selected from the settings page, or even better, through a pop-out dialog (remembering the previously used settings) that appears every time the user uses the feature.

I tend to remove my likes from profiles before unfollowing them, so this is why I came with the idea. It may not be useful for everyone, but it would be a very nice feature to have.

**Comment by austinhuang0131** [comment]
Mass actions will probably trigger Instagram mechanism and ban your account so no
