### ISSUE TITLE
[BUG]Can not open suggested users

### ISSUE THREAD

**Issue by m-wagner98** [austinhuang0131/barinsta#657]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

It is not possible to open "suggested users". Instead, the "Activity" section is displayed. Restarting the app multiple times did not help. 

## Steps
1. Go to "more"
2. Tap on "Suggested Users"
3. Instead of displaying the suggested users, the "Activity" section is displayed. 

## Environment

 - Device: Google Pixel 3a
 - Android version: 11

**Comment by austinhuang0131** [comment]
Cannot reproduce (except the fact that the suggested users window is called "activity" which is just a visual bug)

**Comment by m-wagner98** [comment]
Now I realize. The two sections look very similiar. You are right, it is a visual bug.

**Comment by austinhuang0131** [comment]
Yeah, they use the same fragment cuz I sorta use the notification fragment for everything lol
