### ISSUE TITLE
[FTR] Mute storie and posts

### ISSUE THREAD

**Issue by amuro0079** [austinhuang0131/barinsta#660]
**What is the feature?**
On instagram we can "mute" posts and/or stories from a user we follow. Having this feature in barinsta would be nice. 

**Describe the solution you'd like**
In a profile page, clicking the three dots in the top right corner allows us to block/restrict the user or change the layout. I suggest to add the option to mute the user (and to choose if we want to mute stories, posts or both) and of course, if the user is already muted, the option to unmute him.

**Comment by austinhuang0131** [comment]
personal note

`/api/v1/friendships/mute_posts_or_story_from_follow/` or `/api/v1/friendships/unmute_posts_or_story_from_follow/`

form:

* `_csrftoken`, `_uid`, `_uuid`: see previous implementations
* `target_reel_author_id`: string
* `target_posts_author_id`: string
* `media_id`: string, i assume this is for hiding posts, exact usage unknown
