### ISSUE TITLE
[TASK] JCenter shutting down on May 2021. Check artifacts which will be impacted.

### ISSUE THREAD

**Issue by ammargitham** [austinhuang0131/barinsta#661]
Hi! Today JFrog (which owns Bintray/JCenter) announced that they're sunsetting Bintray/JCenter - the last day to access these repositories will be May 2021. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Since we have jcenter as one of the repositories, we need to check which libraries are affected and either check for alternatives or check if those libraries are migrating to alternative hosts.

**Comment by austinhuang0131** [comment]
Like almost every other Android project, the only affected artifact is `org.jetbrains.trove4j:trove4j:20160824` which is somehow available *only* on JCenter.

**Comment by austinhuang0131** [comment]
Given the widespread appearance of this problem, I guess we should wait later to see if this issue is fixed upstream... Or we can both update to [Arctic Fox Canary 5](https://androidstudio.googleblog.com/2021/01/android-studio-arctic-fox-canary-5.html), if we have a consensus.

**Comment by dejan2609** [comment]
@austinhuang0131 after some more digging: it seems seems that Android Studio version is **_not_** relevant... what it really matters is your Kotlin version: thing is that **Kotlin 1.3** requires that poor `org.jetbrains.trove4j:trove4j:20160824` (available only on JCenter) while **Kotlin 1.4** uses more recent `trove4j` (that were published to a Maven Central).

Please check my new comment (posted few minutes ago 😃): https://github.com/signalapp/Signal-Android/issues/10906#issuecomment-774756560 You can find some alternatives/suggestions there ;)

**Comment by austinhuang0131** [comment]
ok, they say it's moved to maven now, let's try that

**Comment by austinhuang0131** [comment]
ExoPlayer is updated to the latest 2.13.3 as previous versions are not available without JCenter
