### ISSUE TITLE
[BUG] "Liked" toast messages stuck at the bottom of the app

### ISSUE THREAD

**Issue by alin-1** [austinhuang0131/barinsta#672]
It seems to happen pretty randomly. 

- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

## Environment

 - Device: 
 - Android version:

**Comment by austinhuang0131** [comment]
Because it's a snackbar?
