### ISSUE TITLE
[FTR] Grid view layout for stories

### ISSUE THREAD

**Issue by anoopspeaks** [austinhuang0131/barinsta#679]
Implement Grid view with thumbnails (150x150 px) + download button for stories.
 It will reduce data consumption
At present each time you go to stories tab it will preload everything even though videos seems paused but it's loading in background.

**Comment by austinhuang0131** [comment]
> Implement Grid view with thumbnails (150x150 px)

No.

> download button for stories.

Done.

> It will reduce data consumption
> At present each time you go to stories tab it will preload everything even though videos seems paused but it's loading in background.

It would load the video only if you navigate to the video (by clicking the list or scrolling to it).
