### ISSUE TITLE
[FTR] Create DM thread

### ISSUE THREAD

**Issue by pratzyushd** [austinhuang0131/barinsta#69]
**Is your feature request related to a problem? Please describe.**
It seems that I am unable to actually start a DM with someone. I can send a message to anyone I've already contacted, but not actually start a new one.

**Describe the solution you'd like**
We could maybe have a button on the profile saying "DM"

**Describe alternatives you've considered**
We could also put a button in the DM section saying "start new DM" or something similar

**Additional context**
Please let me know if I've just missed a button or option somewhere :)

**Comment by austinhuang0131** [comment]
v19.0-a2 will allow you to start DM from profile page
