### ISSUE TITLE
[FTR] Add message reply/reaction functions in DMs

### ISSUE THREAD

**Issue by UX0l0l** [austinhuang0131/barinsta#705]
Make it possible to reply to messages individually from other people in DMs like in the official app to make it easier to use. And also add the feature to do reaction emojis and double click to like a specific message (optional)

**Comment by austinhuang0131** [comment]
These are implemented in v19.1.0-a1 already.

* Swipe a message to the right to reply.
* Long press a message to react (or like, which is basically just reacting a heart emoji now).

**Comment by UX0l0l** [comment]
oh, I haven't used the alpha version so I didn't know lol
