### ISSUE TITLE
[FTR] GIF Support in DMs ? 

### ISSUE THREAD

**Issue by akashkroy** [austinhuang0131/barinsta#713]
I get it its a work in progress but GIFs in DM will make the chatting experience whole lot better.
Or was the GIF support left out intentionally?

**Comment by austinhuang0131** [comment]
https://github.com/austinhuang0131/barinsta/releases/tag/test-v19.1.0-a1 allows receiving them.

Sending them is planned.

**Comment by ammargitham** [comment]
Added in https://github.com/ammargitham/barinsta/commit/6d73528387e805d2ffdf566a7ee6df663352f463
