### ISSUE TITLE
Dms not working

### ISSUE THREAD

**Issue by spareis** [austinhuang0131/barinsta#716]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

I think the issue came up after the recent update, DMs don't seem to be working. Everything other than that is working. The DMs tab is empty. Clearing data or reinstalling the app didn't fix it.

 - Device: Xiaomi
 - Android version: 10

**Comment by austinhuang0131** [comment]
try https://github.com/austinhuang0131/barinsta/releases/tag/test-v19.1.0-a1

reopen if necessary

**Comment by spareis** [comment]
Yea, the update fixed it. Thanks so much
