### ISSUE TITLE
Fdroid version stuck on 19.0.1

### ISSUE THREAD

**Issue by thejohnha** [austinhuang0131/barinsta#765]
Any plans to update the version on fdroid? 🙏

**Comment by austinhuang0131** [comment]
F-Droid version is on 19.0.5. You need to pull & refresh on the New or Category tab.

**Comment by thejohnha** [comment]
Ahh, sorry. I had to set fdroid to show incompatible versions. After that I saw this:

![Screenshot_20210308_102402.jpg](https://user-images.githubusercontent.com/6325833/110341680-9bf3df80-7ff8-11eb-88de-2122a5d79f76.jpg)

Thanks for your help and awesome app!
