### ISSUE TITLE
Stories not showed

### ISSUE THREAD

**Issue by maxdid** [austinhuang0131/barinsta#768]
From yesterday, I can't view the stories top bar.
I tried to switch account, reinstalling the app, empty the cache but nothing worked.
I've noticed that the loading animation is always present.

**Comment by austinhuang0131** [comment]
Try [v19.1.0-a1](https://github.com/austinhuang0131/barinsta/releases/tag/test-v19.1.0-a1). Reminder:

> Unless specifically instructed by this documentation or the developers, clearing application data/cache or reinstallations (of the same version) will not resolve issues.

(It's on the [FAQ](https://barinsta.austinhuang.me/en/latest/faq) page)

**Comment by maxdid** [comment]
@austinhuang0131 thanks a lot. It has solved the problem.
