### ISSUE TITLE
[FTR] Button Mark the story as seen  in Stories

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#780]
In the DM, there is a button (mark a message as seen) it is convenient, it would be a great (if possible) to implement a similar button for stories. 

P.S Thanks to the developers for the application

**Comment by austinhuang0131** [comment]
Mark story as seen will also mark all *previous active* stories (ie. any active stories before the one you viewed) of the user as seen (since stories are identified by timestamp) so such a button would be misleading and therefore not be implemented.
