### ISSUE TITLE
[BUG] Avatar Size in format  menu Tile Feed only One

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#782]
If you go to the tape and select the Avatar size in the menu, they still remain unchanged (no more no less )
if choice tile one, if choice two tile or more, size work fine

## Environment
 - Device:  19.0.5 (57)
 - Android version: 5.1

**Comment by austinhuang0131** [comment]
Could you explain more coherently?

**Comment by xbvrhlmb** [comment]
> Could you explain more coherently?

![fix](https://user-images.githubusercontent.com/43858033/110994125-fe463a80-8380-11eb-9b76-f523315ffb24.png)
if choice this, avatar size not update.

now I Try use new version v19.1.0 alpha 1  But she crash in almost any movement :)

**Comment by austinhuang0131** [comment]
Well, it's an alpha version, so it's a bit unstable...

Avatar size is not intended to work on waterfall view so I'll hide it

**Comment by xbvrhlmb** [comment]
Yea little bit :)

It is a sorry: (big avatars are a little enrage by 300 dpi

**Comment by xbvrhlmb** [comment]
if use 19.1.0 alpha and use this settings app crashed
if use default settings format, work fine (not cant make crash report)
