### ISSUE TITLE
[FTR] Check after user use erroneous click follow or unfollow

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#786]
If the appendix has such functions as anonymity,  will be great. if user pressed button  subscription or unsubscribe was open the check form before execution (to exclude accidental pressing)

because it can accidentally give out the user :)

**Comment by austinhuang0131** [comment]
Unfollow warning exists for private users, but otherwise it's easily undoable and therefore a warning is quite unnecessary (or bothersome, even).

**Comment by xbvrhlmb** [comment]
Yes, but only for private, but for open no and I, for example, can accidentally press subscribe or unsubscribe 
Yes, you are right possible (or BotheSome, Even). But it can be done as setting on / off
