### ISSUE TITLE
[FTR] Message counter 

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#788]
1) It would be nice to see in the launcher on the icon, on the home screen, message counter

## Example Screenshot 
![launcher_counter](https://user-images.githubusercontent.com/43858033/110985698-6db62d00-8375-11eb-8310-ca61485deae3.png)

2) It would also be convenient to see the message meter in the application itself above the "Personal Message (DM)" button
(It would help see a new message) Knowing the previous figure (since there are no notifications about new posts)

## Example Screenshot 
![counter](https://user-images.githubusercontent.com/43858033/110985979-c71e5c00-8375-11eb-9a54-46229d273125.png)

P.S Many thanks to the developers for work :)

**Comment by ammargitham** [comment]
This is not a standard feature of Android. Only some launchers support it from what I could find online.

**Comment by xbvrhlmb** [comment]
> This is not a standard feature of Android. Only some launchers support it from what I could find online.

as far as I know, this is the default  but since Android 10 

but the main thing, what I write about the counter in the application (second screenshot, at that time I did not see the alpha version) 
so this topic can be closed, since this has already been implemented in alpha)
