### ISSUE TITLE
[FTR] DM voice support

### ISSUE THREAD

**Issue by legkamran** [austinhuang0131/barinsta#79]
Its not showing tagged people and cant play DM audios... If it possible to add send voice message feature, I'll removed original Instagram app...
Share story,photo and videos I can do from browser but its not playing and sending voice messages...
Thanks for great work!

**Comment by austinhuang0131** [comment]
Please fill in title.

Reading DM audios _should_ be supported. Please reply with screenshot.

Sending DM audios... Well, I'm not really down to add a recorder within the app, but I guess I will do it if there is significant demand.

**Comment by legkamran** [comment]
thanks for answer 👍

**Comment by austinhuang0131** [comment]
euh...

> Reading DM audios _should_ be supported. Please reply with screenshot.

Let me make myself clear. I meant that reading DM audios should already be supported currently, and it would be considered a bug if it's not, so please reply with screenshot if that's the case.
