### ISSUE TITLE
[BUG] [ALPHA] Crash Report make empty file

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#793]
Make empty logs files

## Steps
1. Download app in GitHub
2.  install App
3. import only (profile) if import settings to 100% crash
4. App Crash
5. Click button make report
6. Choice Directory (Solid Explorer) directory have access
7. create empty file crash_logs.zip (size 0 B)

## Environment
 - Android version:  5.1
 - App version:  19.1.0-a1 (58)

**Comment by austinhuang0131** [comment]
I need the report text, not file

The report button should be opened by email
