### ISSUE TITLE
[BUG] Count Read Message

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#797]
In the old version there was an icon on unread messages (red circle near the avatar)
even if the message was read, he still remained in the new version of the counter sees this message, and considers them.

I did not understand to the end as it happens, perhaps if I delete my last message in the DM and remain the last from the interlocutor, and then the counter marks them as new.
In other cases, everything works fine.

In stable version (19.0.5) if open tab DM show red circle, if open this DM circle not hide. 
In new alpha version (19.1.0) if i start app, counter show  me  0 new message, if i open tab DM counter see me 2 old message

## Environment
 - App Version :  19.0.5 (57) - 19.1.0-a1 (58)
 - Android Version: 5.1

**Comment by ammargitham** [comment]
Can you provide screenshots from the alpha describing your issue? That will help me in understanding your issue more clearly.

**Comment by xbvrhlmb** [comment]
I do not know how to portray it in the screenshot,
the point is that I see the count of 2 unread messages 
Which I have long read.

![1](https://user-images.githubusercontent.com/43858033/111354448-ffcc7700-868e-11eb-976e-718bed5d1909.png)

In the stable version, they were simply marked with a red circle near the avatar,
That is, in the usual situation when a message comes, a red circle is visible nearby the avatar when the message opens the circle disappears
and in my case a  even if you open message a circle remains (not at all, only in a rare case)
perhaps it works when I read the message then I sent something, and then deleted this message
Then the counter re-sees the old message as a new (Perhaps and maybe not)
