### ISSUE TITLE
[BUG] DM audio can't play

### ISSUE THREAD

**Issue by legkamran** [austinhuang0131/barinsta#80]
I can play audio from browser but its not startiing from the app...
![Screenshot_20200827-134954_InstaGrabber](https://user-images.githubusercontent.com/29841945/91425456-387c3e80-e86c-11ea-8005-f753110874fd.jpg)
![Screenshot_20200827-134956_InstaGrabber](https://user-images.githubusercontent.com/29841945/91425474-3e721f80-e86c-11ea-821d-b523966d07e0.jpg)

Devive : Samsung Galaxy A10 Android 10

**Comment by Shadowspear123** [comment]
Not related.... But how'd you make it that color?

**Comment by austinhuang0131** [comment]
methinks some sort of eye-protection filter

**Comment by legkamran** [comment]
@Shadowspear123  RedMoon you can found it from F-droid
