### ISSUE TITLE
[BUG] Can't log in

### ISSUE THREAD

**Issue by modelfe** [austinhuang0131/barinsta#801]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

I just tried to log into my Instagram account in Barinsta after changing my Instagram account password, and keep getting the following message on the Instagram login page after entering my username and password: 

> We couldn't connect to Instagram. Make sure you're connected to the internet and try again.

I have tried this a few times, with both WiFi and mobile data. The result is the same. I'm not using a VPN or proxy. It doesn't matter if I use my username or email to log in. If I select "Forgot password" it takes me to the forgot password page, so it is able to connect to the internet. My other account is still logged in on Barinsta and is working just fine, and I can log into the affected account in the browser and in the official Instagram app.

 - Device: Nokia 7.2
 - Android version: 10

**Comment by austinhuang0131** [comment]
I assume the error message is within the WebView (browser-like window)? This sounds like an Instagram issue to me...

**Comment by modelfe** [comment]
Yes, in the WebView login page. It does sound like an Instagram issue, I agree. I just thought I would report it here, as I am only experiencing the issue when trying to log in via Barinsta (i.e., I can still log in on the Instagram app and in Firefox).

**Comment by modelfe** [comment]
Okay, I just tried it again and it successfully logged in. I'll put it down to some mysterious upstream Instagram issue. I'm happy for this issue to be closed, unless you'd like any more information etc.

**Comment by austinhuang0131** [comment]
At https://t.me/grabber_app/18134 someone also reported it, so I assume this is spontaneous...
