### ISSUE TITLE
[BUG] Day Night  auto theme 24H

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#805]
I'm not sure if it works in a stable version, but by choosing in the settings "follow the system" day night there is no switching to night mode, always enabled day theme

Maybe it does not work with 24 hours and time?

## Environment
 - Android version:  5.1
 - App version:  19.1.0-a1 (58)

**Comment by austinhuang0131** [comment]
"Follow the system" only works above Android 9.

**Comment by xbvrhlmb** [comment]
> "Follow the system" only works above Android 9.

understood) what prevents to do in time, regardless of the functions android?
if time > 20 = night
if time < 20 = day
