### ISSUE TITLE
[FTR] Change Circle color for Stories if user see stories

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#833]
It would be great to mark the circle with a different color in the application (if the user has viewed all the stories)

(it is within the application that the mark that the user has seen the stories is not meant to server or author stories) 

## Example
i see all stories author, circle change green color to grey
author add new stories circle change color to green again

So I could know what stories I saw, and when author added a new story

**Comment by austinhuang0131** [comment]
The circle is only grey if you have read all the stories, so new stories after that would restore it to new.

**Comment by xbvrhlmb** [comment]
@austinhuang0131 the work only if in settings enable "anonymous view" stories?

**Comment by austinhuang0131** [comment]
yeah, it'll only work if you mark it as seen in the settings

if you're talking about saving seen status locally then that'd be #1008
