### ISSUE TITLE
[BUG] Clicking profile leads to facebook URL

### ISSUE THREAD

**Issue by sigaloid** [austinhuang0131/barinsta#838]
- [X] My app is on the latest version. I understand that any other version is not supported.
- [X] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

Clicking the info button on a DM then clicking the user redirects me to a 404 facebook page

## Steps
1. Open instagram DM info page
2. Click a person's info button
3. Be redirected to FB

## Environment

 - Device: LG G7 thinq
 - Android version: 9

## Additional info

Does not crash, so no crash logs to give. 

Does not occur on the stable version before this

**Comment by austinhuang0131** [comment]
Does the member have a username?

**Comment by sigaloid** [comment]
How can they "not be an instagram user"? Does that mean they logged in with facebook? 

testing on desktop browser leads to "You must log in to continue", so does that also signify a facebook user?

**Comment by austinhuang0131** [comment]
> How can they "not be an instagram user"? Does that mean they logged in with facebook?

The new [Messenger integration thing](https://www.nytimes.com/2020/09/30/technology/instagram-facebook-messenger-integration.html) effectively allows you to message Facebook users.

> testing on desktop browser leads to "You must log in to continue", so does that also signify a facebook user?

For me, those conversations simply don't appear on browser...

Also it's redone in https://github.com/austinhuang0131/barinsta/commit/ee36ba8c35c013be7a476b7b5baf34fd20eaa265 but I doubt there's really a difference

**Comment by sigaloid** [comment]
>On Barinsta's member list, if you do not see a username under the full name, it's probably a Facebook user.

I can see the full username.

>For me, those conversations simply don't appear on browser... 

Well I can definitely use the browser to talk with this person, so I'm not quite sure what it could be... 

Another problem is I cannot see media from this person on latest version (but voice messages works!)! It says the same error as it does when I open it then go back, except it is unopened. I had another draft bug issue but I feel like it could be related since it is the same person. I 

I reverted back to old version for now, I will test with other users that don't have facebook and open media and test it.

**Comment by austinhuang0131** [comment]
Okay, then I guess it's fixed in https://github.com/austinhuang0131/barinsta/commit/ee36ba8c35c013be7a476b7b5baf34fd20eaa265, I guess certain Instagram users have a Facebook ID linked to them now (I thought they were separate)

**Comment by sigaloid** [comment]
Did https://github.com/austinhuang0131/barinsta/commit/ee36ba8c35c013be7a476b7b5baf34fd20eaa265 just get added? don't have this issue on previous stable release. regardless, thanks!

**Comment by austinhuang0131** [comment]
yeah it's not on release

**Comment by sigaloid** [comment]
I mean i didn't have this issue in https://github.com/austinhuang0131/barinsta/releases/tag/v19.0.5

**Comment by austinhuang0131** [comment]
yeah because we redid the DM thingy
