### ISSUE TITLE
[BUG] Images show as expired despite not being expired

### ISSUE THREAD

**Issue by sigaloid** [austinhuang0131/barinsta#843]
- [X] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).
- [X] My app is on the latest version. I understand that any other version is not supported.

Images do not open.
## Steps

1. Receive image (may be related to https://github.com/austinhuang0131/barinsta/issues/838 in that it is from a user that has a FBID, if you want to drop your @ if you know it's not facebook linked so I can test it let me know)
2. try to open by clicking, long pressing, etc
3. it says "expired"

## Environment

 - Device: LG G7 
 - Android version: 9

## Additional info

No logs since no crash

**Comment by austinhuang0131** [comment]
FB user has nothing to do with this. Someone else in Telegram also complained about this so I guess it's a real issue

**Comment by austinhuang0131** [comment]
Actually, you wanna try sending [me](https://instagram.com/austinhuang.me) similar messages so that I can test?

**Comment by sigaloid** [comment]
Sent

**Comment by sigaloid** [comment]
Any chance of a bugfix release for this or should I just compile?

**Comment by austinhuang0131** [comment]
I guess I'll try to release either this week or next week (no major features though). But yeah, if you know how to build-compile-whatever you might as well just grab master and DIY. If I see issues I always fix it on master so
