### ISSUE TITLE
[BUG] StoryViewFragment displaying as title instead of user name

### ISSUE THREAD

**Issue by francopan** [austinhuang0131/barinsta#848]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://barinsta.austinhuang.me/en/latest/faq).

When you open a post from a story and see the comments, when you go back the title is lost.

## Steps

1.  Open a story that displays a post
2.  Click on 'View Post'
3.  Open comments
4.  Press phone's 'back' button until get back to story.
5.  Story title is no longer the user's name, but StoryViewFragment

## Environment

 - Device: Asus Zenfone 5 (2018)
 - Android version: 9

## Additional info
 --

**Comment by ammargitham** [comment]
@austinhuang0131 This should be fixed in https://github.com/austinhuang0131/barinsta/commit/b5e110170977cfbea3b971e6534ccf85691889a6 i think. The onResume() should set the correct title.

**Comment by austinhuang0131** [comment]
@ammargitham no, it doesn't call onResume if you do exactly as the steps say

**Comment by austinhuang0131** [comment]
fixed probably due to PostViewV2Fragment no longer being overlay
