### ISSUE TITLE
[BUG]  Anonymous open profile username valid

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#854]
if not login try open profile, first show profile, if try again show valid username
(username of course valid, and work fine, i try more username for check)

## Steps
1. Open App (no authorization) , and input in search bar username (profile show)
2. go back, open again search bar and input username, open profile (show error valid username)

if add username in "Favorite" and try open, show to error "valid"

## Screenshot
![1](https://user-images.githubusercontent.com/43858033/112380523-24a99580-8cf2-11eb-942a-3ec7b9a3bde7.png)

## Environment

 - App Version: 19.0.5 - 19.1.0 
 - Android version: 5.1

**Comment by austinhuang0131** [comment]
"If so, you may be ratelimited."
