### ISSUE TITLE
[FTR] Save DM's locally

### ISSUE THREAD

**Issue by sigaloid** [austinhuang0131/barinsta#902]
**Is your feature request related to a problem? Please describe.**
Would be nice if DM's could be saved locally. Then loading of DM's would be quicker. For example, it doesn't have to make any message thread requests if the badge number hasn't changed, so I could scroll through DM's without it loading anything from instagram. In addition, rechecking old messages could be locally stored so it doesn't take a while to load every time. 

**Describe the solution you'd like**
Save the DM's in local storage as JSON or something similar, append to it as messages are loaded forwards or backwards. In addition would be nice to have an export or at least a folder where they are stored. 

**Additional context**
Messages are slow to load, the same messages are loaded a lot if you open the app often, and if there is no network connection, they cannot be read.

**Comment by ammargitham** [comment]
This was a thing which was discussed before implementing the new DM module. And we decided against it.

**Comment by sigaloid** [comment]
:disappointed_relieved: okay, closing
