### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by devarshirawal0111** [austinhuang0131/barinsta#939]
First of all, it's a great project. I love it!! It satisfies most of my needs.

I follow many users and sometimes save their posts in my collections. I have been doing that for a few years now. For a last couple of month, I have been looking for a tool that can help me download these collections(and sometimes entire profile) completely.

Your project is awesome and is closest to this particular need. Except it doesn't have an option to download a complete collection, or a complete profile of a user. The closest it gets to is to manually select all the posts and batch download. I haven't looked into the code of the project as I am not a java developer, but I have worked in few other instagram api(s) out there. So I believe it might be one of the harder things to do as the posts might be loading with pagination setup. 

My feature request is to add a **"Select All"** option when selecting the images anywhere and/or **"Download All"** option if possible.

**Comment by austinhuang0131** [comment]
Please use the template next time.

You already work with the API so I assume you know how ratelimiting works. It's unsafe to implement such feature and I can't expect people to "use responsibly". Also addiction.
