### ISSUE TITLE
Can't access to private messages (PMs)

### ISSUE THREAD

**Issue by moshpirit** [austinhuang0131/barinsta#943]
I can see the list of conversations with the first line of each last message but when I open them they appear empty.

**Comment by austinhuang0131** [comment]
Not reproducible on my end. Which version are you on?

**Comment by moshpirit** [comment]
I've tried this on two devices (both with last F-droid Barista version):

- Xiaomi Note 7 Pro. Android 10.
- Samsung Tab S4. Android 10.

None have any Google account and almost no Gapps. 

But I've opened one conversation and pressed the information (i) button. It crashed and then loaded them like nothing happened when opened the app again. In both devices. No idea of what has just happened.

**Comment by austinhuang0131** [comment]
I assume you're accessing threads from the inbox fragment (aka. the one on the navbar). It's working for me normally and I have not heard other reports (excluding outages).

* Is this happening for *all* your convos, or just specific ones?
* Does accessing the inbox from browser work? (Any device, doesn't have to be a phone)
* Do you know how to logcat?

(Also reminder that Gapps is never a factor for apps on F-Droid)

**Comment by moshpirit** [comment]
Thanks for replying that fast! Yes, it's the one on the navbar.
- All the convos
- I didn't try it, should I try it now? The issue seems fixed. Which, BTW, it's been like this for more than a week (just informing 😊) 
- No, I don't, but will it give me the log of a past event (not showing the content)?

You're right! Haha

**Comment by austinhuang0131** [comment]
So you say this issue is fixed on Barinsta now?

**Comment by moshpirit** [comment]
Yes, after the crash it was solved
