### ISSUE TITLE
[FTR] Back Button for Choice Menu in DM

### ISSUE THREAD

**Issue by xbvrhlmb** [austinhuang0131/barinsta#968]
if join in DM and open dialog click message you have menu "Resend" "Copy" "Delete message" an other
but if user try use button "Back" in phone then nothing happens 

That is, this menu does not hide and block the interface (until the user chooses something from the menu) 

Android Version: 5.1
App Version: 19.2.0-github_release (61)

**Comment by austinhuang0131** [comment]
not reproducible

**Comment by xbvrhlmb** [comment]
![bug1](https://user-images.githubusercontent.com/43858033/113568385-212edc00-9619-11eb-9330-d58c9cf3d3c5.png)
Did you check this menu?
Perhaps this is only me, hardware button back (work fine in other menu) 
but when menu open. interface block
The touch buttons back and others in the interface besides this menu (that is, there is a lock) until I choose something from the menu.

**Comment by austinhuang0131** [comment]
Yes, this menu. I'm using standard bottom back button and it works. So it's probably device-specific
