### ISSUE TITLE
[BUG] comments in hashtag browser don't load

### ISSUE THREAD

**Issue by Redn2000** [austinhuang0131/barinsta#974]
Android version: 9
Barintsa version: 19.1.0
While browsing a tag of some kind the posts are viewable, as well as the description, however the comments are not.
To reproduce: click on a tag of a post and wait for it to load posts with said tag. Then click on the post and try to open the comments if there are any. They'll fail to load once opened.

**Comment by austinhuang0131** [comment]
Anonymous?

**Comment by Redn2000** [comment]
> Anonymous?

Ah, sorry. This is while logged into an existing account.

**Comment by austinhuang0131** [comment]
cannot reproduce this... might just be a specific post?

**Comment by Redn2000** [comment]
> cannot reproduce this... might just be a specific post?

I filed this issue without realizing there was a new version released recently. After updating, it seems to have been corrected. I look forward to your app being on the play store soon.
